---
env:
    name: BipedalWalker-v3
    video_path: video
    log_video: False
    n_envs: 8
    efficient_envvec: False
    log_episode: True
    auto_reset: True
    seed: 0
model:
    encoder:
        has_cnn: True
        # units_list: [256]
        # activation: elu
    rssm:
        stoch_size: 30
        deter_size: 200
        hidden_size: 200
        activation: elu
    reward:
        units_list: [400, 400]
        activation: elu
    actor:
        units_list: [400, 400, 400, 400]
        activation: elu
        init_std: 5
        min_std: 1.e-4
        mean_scale: 5
    value:
        units_list: [400, 400, 400]
        activation: elu
    decoder:
        has_cnn: True
        # units_list: [256]
        # activation: elu
    terminal:
        units_list: [400, 400, 400]
        activation: elu
agent:
    algorithm: &algo dreamer
    polyak: .995
    precision: 32
    batch_size: &bs 256
    length: &length 50

    MAX_STEPS: 2.e+7
    TIME_INTERVAL: 100
    LOG_INTERVAL: 10000
    TRAIN_INTERVAL: 1000
    TIMER: False
    n_updates: 8

    # model
    free_nats: 3.
    kl_scale: 1.
    term_scale: 10.
    # behavior
    horizon: 15
    gamma: &gamma 0.99
    lambda: .95
    epsilon: .3


    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: mse                          # huber or mse
    tbo: False                               # transformed Bellman Operator

    # arguments for optimizer
    optimizer: adam
    precision: 32
    clip_norm: 100
    weight_decay: 0
    model_lr: 6.e-4
    actor_lr: 8.e-5
    value_lr: 8.e-5
    epsilon: 1.e-8

replay:
    type: episodic                      # proportional or uniform

    # arguments for general replay
    batch_size: *bs
    length: *length
    max_episodes: 500