---
env:
    name: LunarLander-v2
    video_path: video
    log_video: False
    n_envs: 1
    efficient_envvec: True
    seed: 0
model:
    rssm:
        stoch_size: 64
        deter_size: 64
        hidden_size: 64
        activation: elu
    reward:
        units_list: [64]
    actor:
        units_list: [64]
        activation: elu
        init_std: 5
        min_std: 1.e-4
    value:
        units_list: [64]
        activation: elu
    temperature:
        temp_type: 'variable'
        value: .2
agent:
    algorithm: &algo asap-sac
    gamma: &gamma 0.99
    polyak: .995
    evaluation: False
    kl_coef: .1
    act_eps: 0
    
    # timer&interval
    MAX_STEPS: 2.e+7
    TIME_INTERVAL: 100
    LOG_INTERVAL: 100000
    timer: True

    # model
    free_nats: 3.
    kl_scale: 1.
    term_scale: 10.

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: mse                          # huber or mse
    tbo: False                               # transformed Bellman Operator

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    actor_lr: 1.e-3
    q_lr: 1.e-3
    temp_lr: 1.e-3
    epsilon: 1.e-8
    # clip_norm: 10
    
    # arguments for PER
    per_alpha: 0.5
    per_epsilon: 1.e-4

replay:
    type: uniform                      # proportional or uniform

    # arguments for general replay
    n_steps: 1
    gamma: *gamma
    batch_size: 512
    min_size: 5e4
    capacity: 1e6
