---
algorithm: &algo dynamics
name: dynamics
info: dynamics

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
    algorithm: *algo

    MAX_STEPS: 3e7
    n_steps: &nsteps 10
    LOG_PERIOD: 2e5

    n_envs: 64

    model_warm_up: True
    model_warm_up_steps: 5e4

env:
    env_name: &env_name grf-academy_3_vs_1_with_keeper
    representation: simple115v2
    rewards: scoring,checkpoints
    render: False
    write_full_episode_dumps: False
    write_video: False
    dump_frequency: 1000
    logdir: results/grf
    extra_players: null
    number_of_left_players_agent_controls: 3
    number_of_right_players_agent_controls: 0
    add_role_to_obs: False
    shared_ckpt_reward: False
    shared_reward: True

    max_episode_steps: 400
    use_action_mask: False
    uid2aid: null
    shared_policy: False

    n_runners: &nrunners 8
    n_envs: &nenvs 8

    use_sample_mask: True
    use_idx: False
    use_hidden: False
    use_event: False
    agentwise_global_state: False
    timeout_done: &td False

agent: {}

monitor:
    use_tensorboard: True

strategy:
    algorithm: *algo
    train_loop:
        ergodic: False
        training_data_size: &ds 1e5
        valid_data_size: 6400
        wp_n_epochs: 2000
        n_epochs: &nepochs 500

model:
    aid: 0
    n_elites: 5
    global_state_type: obs
    rn_std: .1
    model_norm_obs: &obs_norm True
    deterministic_trans: True
    model_loss_type: &mlt mse
    obs_clip: 10

    edynamics:
        nn_id: edynamics
        n_models: &n 1
        in_config:
            out_size: &embed 128
        tx_config:
            n_blocks: 4
            attn_config:
                n_heads: 4
        model_out_config:
            model_type: continuous
            max_logvar: .5
            min_logvar: -10
        model_config:
            units_list: [128]
            activation: relu
        reward_config:
            units_list: [128]
            activation: relu

loss:
    model_loss_type: *mlt
    n_models: *n

    model_coef: 1
    reward_coef: 1
    discount_coef: 1

    model_prio_coef: 1
    reward_prio_coef: 1
    discount_prio_coef: 1

trainer:
    algorithm: *algo
    aid: 0
    trust_threshold: null
    timeout_done: *td

    theta_opt:
        opt_name: adam
        lr: 5e-4
        clip_norm: 10
        eps: 1e-5
        weight_decay: 1e-5

actor: {}


buffer:
    type: uniform

    model_norm_obs: *obs_norm
    n_runners: *nrunners
    n_envs: *nenvs
    max_size: *ds
    min_size: 1e3
    n_recency: 1e3
    batch_size: 256
    sample_size: 1

    max_steps: 1

    sample_keys: 
        - obs
        - action
        - reward
        - discount
        - reset
