---
algorithm: &algo model
name: model
info: model

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
    algorithm: *algo

    MAX_STEPS: 1e8
    n_steps: &nsteps 100
    LOG_PERIOD: 2e5

    n_envs: &nenvs 64

env:
    env_name: &env_name magw-escalation
    n_runners: &nrunners 1
    n_envs: *nenvs
    max_episode_steps: 50
    reward_scale: .1
    population_size: 1
    timeout_done: &td False

    uid2aid: [0, 1]

agent: {}

monitor:
    use_tensorboard: True

strategy:
    algorithm: *algo
    train_loop: {}

model:
    aid: 0
    n_elites: 1
    global_state_type: concat
    rn_std: .1

    emodels:
        nn_id: emodels
        n: &n 1
        units_list: [256, 256]
        activation: relu
        norm: layer
        out_config:
            type: discrete
            n_classes: 5
    reward:
        nn_id: reward
        out_size: 1
        units_list: [256, 256]
        activation: relu
        norm: layer
        out_scale: .01
    discount:
        nn_id: discount
        out_size: 1
        units_list: [256, 256]
        activation: relu
        norm: layer

loss:
    model_loss_type: discrete
    n: *n

    model_coef: 1
    reward_coef: 1
    discount_coef: 1

trainer:
    algorithm: *algo
    aid: 0
    n_epochs: &nepochs 25
    timeout_done: *td

    model_opt:
        opt_name: adam
        lr: 5e-4
        clip_norm: null
        eps: 1e-5

actor: {}


buffer:
    type: ac

    n_runners: *nrunners
    n_envs: *nenvs
    n_steps: 10
    batch_size: 128

    sample_keys: 
        - obs
        - action
        - reward
        - discount
        - reset
