---
algorithm: &algo dynamics
name: dynamics
info: dynamics

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
    algorithm: *algo

    MAX_STEPS: 3e7
    n_steps: &nsteps 10
    LOG_PERIOD: 2e5

    n_envs: &nenvs 64

env:
    env_name: &env_name ma_mujoco-HalfCheetah_2x3
    n_runners: &nrunners 1
    n_envs: *nenvs
    max_episode_steps: 1000
    population_size: 1
    timeout_done: &td False

    uid2aid: [0, 1]

agent: {}

monitor:
    use_tensorboard: True

strategy:
    algorithm: *algo
    train_loop:
        ergodic: False
        n_epochs: &nepochs 100

model:
    aid: 0
    n_elites: 1
    global_state_type: obs
    rn_std: .1
    obs_normalization: &obs_norm True
    deterministic_pred: True
    model_loss_type: &mlt mse
    stoch_trans: True

    emodels:
        nn_id: emodels
        n_models: &n 1
        units_list: [200, 200, 200, 200]
        activation: relu
        norm: layer
        out_config:
            type: continuous
            max_logvar: .5
            min_logvar: -10
    reward:
        nn_id: reward
        out_size: 1
        units_list: [200, 200, 200, 200]
        activation: relu
        norm: layer
        out_scale: .01
        balance_dimension: True
        obs_units_list: [128]
        action_units_list: [64]
    discount:
        nn_id: discount
        out_size: 1
        units_list: [200, 200]
        activation: relu
        norm: layer

loss:
    model_loss_type: *mlt
    n_models: *n
    obs_normalization: *obs_norm
    
    model_coef: 1
    reward_coef: 1
    discount_coef: 1

trainer:
    algorithm: *algo
    aid: 0
    trust_threshold: 1000
    timeout_done: *td
    obs_normalization: *obs_norm

    model_opt:
        opt_name: adam
        lr: 5e-4
        clip_norm: 10
        eps: 1e-5

actor: {}


buffer:
    type: uniform

    n_runners: *nrunners
    n_envs: *nenvs
    max_size: 1e5
    min_size: 5e3
    batch_size: 256
    sample_size: 1

    max_steps: 1

    sample_keys: 
        - obs
        - action
        - reward
        - discount
        - reset
