---
env:
    name: dmc_walker_walk
    size: [100, 100]
    n_envs: 1
    frame_skip: 2
    frame_stack: 3
    precision: &prec 16
model:
    encoder:
        out_size: &zsize 50
    actor:
        units_list: [256, 256, 256, 256]
        norm: none
        activation: relu
        LOG_STD_MIN: -20
        LOG_STD_MAX: 2
    q:
        units_list: [256, 256]
        norm: none
        activation: relu
    temperature:
        temp_type: 'variable'
        value: .1
    curl:
        norm: layer
        out_size: *zsize
agent:
    algorithm: &algo curl
    gamma: &gamma .99
    batch_size: &bs 128
    q_polyak: .99
    encoder_polyak: .95
    act_eps: 0
    # target_entropy: .5                      # tune this param for discrete actions
    
    MAX_STEPS: 1e6
    LOG_PERIOD: 1000
    actor_update_period: 2

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    obs_shape: [84, 84]
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    actor_lr: 1e-3
    q_lr: 1e-3
    curl_lr: 1e-3
    temp_lr: 1e-4
    
    # arguments for PER
    per_alpha: .5
    per_epsilon: 1e-4

replay:
    type: uniform                      # per or uniform
    # arguments for PER
    beta0: .4
    beta_steps: 5e4
    to_update_top_priority: True

    # arguments for general replay
    n_steps: 1
    gamma: *gamma
    batch_size: *bs
    min_size: 1e3
    capacity: 1e5
    has_next_obs: False
