---
env:
    name: procgen_coinrun
    size: [64, 64]
    n_envs: 1
    frame_skip: 8
    frame_stack: 3
    precision: &prec 16
model:
    encoder:
        obs_shape: &obsshape [84, 84]
        norm: layer
        dense_act: null
        z_size: &zsize 50
    actor:
        z_size: *zsize
        units_list: [1024, 1024]
        norm: null
        activation: relu
        LOG_STD_MIN: -10
        LOG_STD_MAX: 2
    q:
        units_list: [1024, 1024]
        norm: null
        activation: relu
    temperature:
        temp_type: 'variable'
        value: 0
    curl:
        # units_list: []
        # activation: relu
        z_size: *zsize
agent:
    algorithm: &algo curl
    replay_type: &replay 'uniform'
    gamma: &gamma .99
    batch_size: &bs 128
    q_polyak: .99
    encoder_polyak: .95
    act_eps: 0

    MAX_STEPS: 1e6
    LOG_PERIOD: 1000
    actor_update_period: 2

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    RECORD: True

    obs_shape: *obsshape
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    actor_lr: 1e-3
    value_lr: 1e-3
    curl_lr: 1e-3
    temp_lr: 1e-4
    
    # arguments for PER
    per_alpha: .5
    per_epsilon: 1e-4

replay:
    replay_type: *replay
    # arguments for PER
    beta0: .4
    beta_steps: 5e4
    to_update_top_priority: True

    # arguments for general replay
    n_steps: 1
    gamma: *gamma
    batch_size: *bs
    min_size: 1e3
    capacity: 1e5
    has_next_obs: True
