---
env:
    name: procgen_miner
    n_envs: &ne 1
    frame_skip: 1
    frame_stack: 4

model:
    encoder: 
        cnn_name: procgen
        obs_range: [0, 1]
        filters: [32, 64, 64, 64]
        n_blocks: [1, 1, 1, 1]
        kernel_initializer: glorot_uniform
        stem: conv_maxblurpool
        subsample: conv_maxblurpool
        block: resv1
        block_kwargs:
            conv: conv2d
            filter_coefs: []
            kernel_sizes: [3, 3]
            norm: null
            norm_kwargs: {}
            activation: relu
            am: cbam
            dropout_rate: 0
            rezero: False
        sa: conv_sa
        sa_pos: []
        sa_kwargs:
            key_ratio: 1
            val_ratio: 1
            downsample_ratio: 1
        deter_stoch: True
        belief: False
        out_activation: null
        out_size: null
    actor:
        units_list: [512]
        layer_type: dense
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu
    q:
        units_list: [512]
        layer_type: dense
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu
        tau_embed_size: 64
        phi_activation: relu
        K: &K 32
    temperature:
        temp_type: constant
        value: .01
    twin_q: False
    reward_entropy: True
        
agent:
    algorithm: &algo sacdiqn
    replay_type: &replay uniform
    gamma: &gamma .99
    batch_size: &bs 64
    n_steps: &nsteps 3      # n-step target
    precision: &prec 32
    schedule_act_eps: False
    act_eps: 0
    eval_act_eps: 0
    target_entropy_coef: .8
    
    MAX_STEPS: 8e6
    TRAIN_PERIOD: 64
    EVAL_PERIOD: 1e6
    LOG_PERIOD: 5e4
    N_UPDATES: 1
    RECORD: True

    normalize_reward: False

    # IQN params
    N: 32                # N in paper, num of quantiles for online quantile network
    N_PRIME: 32          # N' in paper, num of quantiles for target quantile network
    K: *K               # K in paper, num of quantiles for action selection
    KAPPA: 1            # 𝜅 in paper, used as the threshold for the huber loss

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    target_update_period: 1500
    tbo: False

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    q_lr: 2.5e-4
    actor_lr: 2.5e-4
    temp_lr: 2.5e-4
    prior_lr: 1.e-3
    epsilon: 3.125e-4
    
    # arguments for PER
    per_alpha: .5
    per_epsilon: 1e-4
    use_is_ratio: &is False

replay:
    replay_type: *replay
    seqlen: 50
    n_envs: *ne
    # arguments for PER
    beta0: .4
    beta_steps: 5e4
    to_update_top_priority: True
    use_is_ratio: *is

    # arguments for general replay
    n_steps: *nsteps
    max_steps: 5
    gamma: *gamma
    batch_size: *bs
    min_size: 1600
    capacity: 2.5e5
    has_next_obs: False
