---
env:
    name: &env_name atari_MontezumaRevenge
    n_workers: 12
    n_envs: &nenvs 10
    seed: 0
    frame_stack: True

model:
    cnn: nature
    kernel_initializer: orthogonal
    activation: relu
    init_std: 1

agent:
    algorithm: &algo rnd
    precision: &prec 16
    gamma_int: &gi .99
    gamma_ext: &ge .999

    MAX_STEPS: 1e10
    N_STEPS: &nsteps 128
    N_UPDATES: 4
    N_MBS: &nmbs 4
    LOG_PERIOD: 200
    EVAL_PERIOD: 2000
    max_kl: 0            # early stop when max_kl is violated. 0 or null suggests unbound

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    ac_lr: 1e-4
    pred_lr: 1e-4
    clip_norm: 0
    # arguments for loss
    clip_range: .1          # clip range for ppo
    entropy_coef: .001
    v_coef: 1
    pred_frac: .25  # fraction of experiences used for predictor update

buffer:
    precision: *prec
    gamma_int: *gi
    gamma_ext: *ge
    int_coef: 1
    ext_coef: 2
    lam: .95
    n_envs: *nenvs
    N_STEPS: *nsteps
    N_MBS: *nmbs        # number of minibatches
    # mini-batch size = n_workers * n_envs * epslen / n_mbs
