---
env:
    name: &env_name procgen_coinrun
    n_workers: 1
    n_envs: &nenvs 8
    seed: 0
    frame_stack: 2
    np_obs: True
    gray_scale: False

model:
    cnn_name: impala
    actor_units: [256]
    critic_units: [256]
    norm: none
    kernel_initializer: orthogonal
    activation: relu
    init_std: 1

agent:
    algorithm: &algo tppo
    precision: 16

    MAX_STEPS: 8e6
    N_STEPS: &nsteps 256
    N_UPDATES: 3
    N_MBS: &nmbs 4
    LOG_PERIOD: 100
    EVAL_PERIOD: 500
    max_kl: 0            # early stop when max_kl is violated. 0 suggests no bound

    normalize_obs: False
    normalize_reward: True

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    RECORD: True
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 5e-4
    clip_norm: 0
    # arguments for loss
    clip_range: .0008          # clip range for tppo
    kl_weight: 20
    entropy_coef: .01
    value_coef: .5

buffer:
    adv_type: gae     # nae or gae
    gamma: .99
    lam: .95
    n_envs: *nenvs
    N_STEPS: *nsteps
    N_MBS: *nmbs        # number of minibatches
    # mini-batch size = n_workers * n_envs * epslen / n_mbs
