---
env:
    name: atari_pong
    precision: &prec 32
    life_done: True
    sticky_action: False
    seed: 0
model:
    q:
        cnn: ftw
        v_units: [256]
        a_units: [256]
        activation: relu
        layer_type: noisy
        duel: False
agent:
    algorithm: &algo d3qn
    gamma: 0.99
    precision: *prec
    batch_size: &bs 50

    # These params are not supported here, see seed1
    store_state: False
    burn_in: False
    batch_len: &bl 50
    burn_in_len: 20
    schedule_eps: False
    act_eps: 0

    MAX_STEPS: 1e7          # maximum training steps
    TRAIN_INTERVAL: 16          # #frames = 4 agent step when frame skip = 4
    EVAL_INTERVAL: 5e5
    LOG_INTERVAL: 1e5

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: huber   # huber or mse
    target_update_freq: 32000               # #frames = 8000 agent step when frame skip = 4
    tbo: False                              # transformed Bellman Operator
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 6.25e-5
    clip_norm: 10
    epsilon: 1.5e-4

    # arguments for PER
    per_alpha: 0.5
    per_epsilon: 1e-4

replay:
    type: episodic      # uniform, proportional

    # arguments for general replay
    gamma: *gamma
    batch_size: *bs
    batch_len: *bl
    max_episodes: 800
    min_episodes: 5
    save: True