---
env:
    name: BipedalWalker-v3
    seed: 0
model:
    actor:
        units_list: [512, 256]
        norm: none
        activation: relu
        init_std: 5
        min_std: 1.e-4
        mean_scale: 5
    q:
        units_list: [512, 256]
        norm: none
        activation: relu
    temperature:
        temp_type: 'variable'
        value: 1
agent:
    algorithm: &algo sac2
    gamma: &gamma .99
    polyak: .995
    act_eps: 0
    # target_entropy: .5                      # tune this param for discrete actions
    
    MAX_STEPS: 3e+6
    LOG_INTERVAL: 10000

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    actor_lr: 3e-4
    q_lr: 3e-4
    temp_lr: 3e-4
    
    # arguments for PER
    per_alpha: .5
    per_epsilon: 1e-4

replay:
    type: uniform                      # proportional or uniform
    # arguments for PER
    beta0: .4
    beta_steps: 5e+4
    to_update_top_priority: True

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: 256
    min_size: 1e+4
    capacity: 1e+6
    has_nth_obs: False
