---
algorithm: &algo il
name: il
info: il

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
  algorithm: *algo
  filename: ma_mujoco-HalfCheetah_2x3.pkl

  MAX_STEPS: 5e6
  n_steps: &nsteps 100
  LOG_PERIOD: 1e5
  EVAL_PERIOD: null

  n_eval_envs: 100
  RECORD_VIDEO: False
  N_EVAL_EPISODES: 1
  size: [256, 256]

  model_rollout_type: sim
  compute_return_at_once: False
  ignore_ratio_for_ego: False
  perm: null

env:
  env_name: &env_name mujoco-Walker2d-v3
  n_runners: &nrunners 1
  n_envs: &nenvs 1
  max_episode_steps: 1000
  to_multi_agent: True
  timeout_done: &td False

agent: {}

monitor:
  use_tensorboard: True

strategy:
  algorithm: *algo
  train_loop: {}

model:
  aid: 0
  joint_log_prob: False
  gamma: &gamma .99

  policy:
    nn_id: policy
    units_list: [64, 64]
    w_init: orthogonal
    activation: tanh
    norm: null
    out_scale: .01
    rnn_type: &prnn null
    rnn_units: 64
    out_act: tanh
    init_std: .2
    sigmoid_scale: True
    std_x_coef: 1.
    std_y_coef: .5
    use_feature_norm: False

loss:
  # hyperparams for value target and advantage
  prnn_bptt: 10

trainer:
  algorithm: *algo
  aid: 0
  n_runners: *nrunners
  n_envs: *nenvs
  n_steps: *nsteps
  debug: False

  theta_opt:
    opt_name: adam
    lr: 3e-4
    clip_norm: 10
    eps: 1e-5

actor:
  update_obs_rms_at_execution: False
  update_obs_at_execution: False
  rms:
    obs:
      obs_names: [obs]
      obs_normalized_axis: [0, 1]
      obs_normalized_ndim: 2
      normalize_obs: True
      obs_clip: 10
    reward:
      reward_normalized_axis: [0, 1] # reward is normalized at once with the sequential dimension
      reward_normalized_ndim: 1
      normalize_reward: False
      update_reward_rms_in_time: False
      gamma: *gamma

buffer:
  type: uniform

  recent_primal_replay: False
  detached: False

  n_runners: *nrunners
  n_envs: *nenvs
  max_size: 1e6
  min_size: 1e3
  batch_size: 256
  sample_size: 1
  max_steps: 1

  sample_keys: &sk
    - obs
    - action
    - reward
    - discount
    - reset
