---
algorithm: &algo zero_ir
name: zero_ir

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
    algorithm: *algo

    MAX_STEPS: 5e7
    n_steps: &nsteps 32
    LOG_PERIOD: 5e5
    EVAL_PERIOD: 5e6

    RECORD_VIDEO: True
    N_EVAL_EPISODES: 1
    size: [256, 256]

env:
    env_name: &env_name grid_world-staghunt
    n_runners: &nrunners 1
    n_envs: &nenvs 64
    max_episode_steps: 50
    share_reward: False
    stag_stay_still: True

    uid2aid: [0, 0]
    use_idx: True
    use_hidden: True
    use_event: False

agent: {}

strategy:
    algorithm: *algo
    train_loop:
        use_dataset: &dataset False
        K: &K 1
        L: &L 0
        extra_meta_step: &ems 0 # 0/1

model:
    aid: 0
    rnn_type: &rnn null
    sample_size: *nsteps
    K: *K
    L: *L
    rl_reward: &rlreward sum
    gamma: &gamma .99
    meta_reward_type: intrinsic
    extra_meta_step: *ems

    encoder: 
        nn_id: null
    rnn:
        nn_id: *rnn
        units: 64
        kernel_initializer: orthogonal
        recurrent_initializer: orthogonal
        use_ln: True
    policy:
        nn_id: policy
        units_list: [64, 64]
        kernel_initializer: orthogonal
        activation: relu
        norm: null
        eval_act_temp: 1
        out_gain: .01
        indexed: head
        indexed_config:
            use_shared_bias: False
            use_bias: True
            kernel_initializer: orthogonal
            activation: relu
    value:
        nn_id: value
        units_list: [64, 64]
        kernel_initializer: orthogonal
        activation: relu
        norm: null
        indexed: head
        indexed_config:
            use_shared_bias: False
            use_bias: True
            kernel_initializer: orthogonal
            activation: relu
    meta_reward: 
        nn_id: value
        units_list: [64, 64]
        kernel_initializer: orthogonal
        activation: relu
        norm: null
        out_act: atan
        indexed: head
        indexed_config:
            use_shared_bias: False
            use_bias: True
            kernel_initializer: orthogonal
            activation: relu
    outer_value:
        nn_id: value
        units_list: [64, 64]
        kernel_initializer: orthogonal
        activation: relu
        norm: null
    meta:
        nn_id: meta
        pg_coef:
            outer: 1
            default: 1
            init: null
            act: sigmoid
        entropy_coef:
            outer: 5e-2
            default: 5e-2
            init: null
            act: sigmoid
        value_coef:
            outer: .5
            default: .5
            scale: 1
            bias: 0
            init: null
            act: sigmoid
        gamma: 
            outer: *gamma
            default: *gamma
            scale: 1
            bias: 0
            init: null
            act: sigmoid
        lam:
            outer: .95
            default: .95
            scale: 1
            bias: 0
            init: null
            act: sigmoid
        reward_scale:
            outer: 1
            default: 1
            scale: 1
            bias: 0
            init: null
            act: tanh
        reward_bias:
            outer: 0
            default: 0
            scale: 1
            bias: 0
            init: null
            act: null
        reward_coef:
            outer: 1
            default: 1
            scale: 1
            bias: 0
            init: null
            act: tanh

loss:
    rl:
        # hyperparams for value target and advantage
        target_type: gae
        c_clip: 1
        rho_clip: 1
        adv_type: vtrace
        norm_adv: True

        # hyperparams for policy optimization
        pg_type: ppo
        ppo_clip_range: .2
        use_dice: False
        dice_axis: null
        dice_lam: 1
        kl: reverse
        kl_coef: 1
        policy_life_mask: True

        # hyperparams for value learning
        value_loss: mse
        value_clip_range: .2
        value_life_mask: False
        stop_target_grads: False

        joint_objective: True
    meta:
        # hyperparams for value target and advantage
        target_type: gae
        c_clip: 1
        rho_clip: 1
        adv_type: vtrace
        norm_adv: True
        norm_meta_adv: True

        # hyperparams for policy optimization
        pg_type: ppo
        ppo_clip_range: .2
        use_dice: False
        dice_axis: null
        dice_lam: 1
        kl: reverse
        kl_coef: 1
        policy_life_mask: True

        # hyperparams for value learning
        value_loss: mse
        value_clip_range: .2
        value_life_mask: False
        stop_target_grads: False

        # hyperparams for meta-learning
        meta_reward_coef: 0
        joint_objective: True

trainer:
    algorithm: *algo
    aid: 0
    n_runners: *nrunners
    n_envs: *nenvs
    n_epochs: &nepochs 4
    n_mbs: &nmbs 1
    n_meta_epochs: 1
    sample_size: *nsteps         # BPTT length
    timeout_done: &td True
    meta_type: plain
    K: *K
    L: *L
    msmg_type: avg
    extra_meta_step: *ems
    store_state: True
    event_done: False
    rl_reward: *rlreward

    optimizer:
        opt_name: adam
        schedule_lr: False
        lr: 3e-3
        # rho: .99
        clip_norm: .5
        epsilon: 1e-5
    meta_opt:
        opt_name: adam
        schedule_lr: False
        lr: 1e-4
        clip_norm: .5
        epsilon: 1e-4
        weight_decay: null

actor:
    update_obs_rms_at_execution: False
    update_obs_at_execution: False
    rms:
        obs_names: [obs, hidden_state]
        obs_normalized_axis: [0, 1, 2]
        reward_normalized_axis: [0, 1, 2]
        normalize_obs: True
        obs_clip: 10
        normalize_reward: False
        update_reward_rms_in_time: False
        gamma: *gamma

buffer:
    type: ppo
    use_dataset: *dataset

    n_runners: *nrunners
    n_envs: *nenvs
    n_steps: *nsteps
    sample_size: *nsteps
    queue_size: 2
    K: *K
    L: *L
    extra_meta_step: *ems
    timeout_done: *td
    rnn_type: *rnn

    sample_keys: 
        - obs
        - idx
        # - event
        - hidden_state
        - action
        - value
        - reward
        - discount
        - reset
        - mu_logprob
        - mu
        - mask
        - h
        - c
