---
env:
    is_deepmind_env: True
    name: BreakoutNoFrameskip-v4
    video_path: video
    log_video: False
    n_envs: 4
    seed: 0
model:
    q:
        cnn: impala
        v_units: [256]
        a_units: [256]
agent:
    algorithm: &algo asap2-dqn
    gamma: &gamma 0.99

    # distributed algo params
    n_workers: 4
    LOG_INTERVAL: 10
    timer: True

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: agent

    loss_type: huber                          # huber or mse
    target_update_freq: 2500

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    learning_rate: 6.25e-5
    clip_norm: 40
    epsilon: 1.e-4

    # arguments for PER
    per_alpha: 0.5
    per_epsilon: 1.e-4

replay:
    type: uniform                      # proportional or uniform
    # arguments for PER
    beta0: 0.4
    beta_steps: 5e4
    to_update_top_priority: False

    # hacking
    # normalize_reward: False
    # reward_scale: 5
    # reward_clip: 50

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: 32
    min_size: 5e4
    capacity: 1e6
