---
env:
    name: &env_name atari_MsPacman
    n_workers: 1
    n_envs: &nenvs 32
    sticky_actions: False
    frame_skip: 4
    frame_stack: 4
    life_done: True
    reward_clip: False
    np_obs: True
    seed: 0

model:
    cnn_name: nature
    actor_units: [256]
    critic_units: [256]
    norm: none
    kernel_initializer: orthogonal
    activation: relu
    init_std: 1

agent:
    algorithm: &algo ppo
    precision: &prec 32

    MAX_STEPS: 1e10
    N_STEPS: &nsteps 256
    N_UPDATES: 2
    N_MBS: &nmbs 4
    LOG_PERIOD: 100
    EVAL_PERIOD: 500
    max_kl: .1            # early stop when max_kl is violated. 0 suggests no bound

    normalize_obs: False
    normalize_reward: True

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    RECORD: True
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 2.5e-4
    clip_norm: .5
    # arguments for loss
    clip_range: .1          # clip range for ppo
    entropy_coef: .01
    value_coef: .5

buffer:
    adv_type: gae     # nae or gae
    precision: *prec
    gamma: .99
    lam: .95
    n_envs: *nenvs
    N_STEPS: *nsteps
    N_MBS: *nmbs        # number of minibatches
    # mini-batch size = n_workers * n_envs * epslen / n_mbs
