---
env:
    name: &env_name Walker2d-v3
    n_workers: 1
    n_envs: &nenvs 8
    seed: 0
    precision: &prec 32

model:
    cnn_name: none
    actor_units: &u [64, 64]
    critic_units: *u
    norm: none
    kernel_initializer: orthogonal
    activation: relu
    init_std: 1

agent:
    algorithm: &algo ppo
    precision: *prec

    MAX_STEPS: 5e7
    N_STEPS: &nsteps 256
    N_UPDATES: 4
    N_MBS: &nmbs 4
    LOG_PERIOD: 100
    EVAL_PERIOD: 1000
    max_kl: .1            # early stop when max_kl is violated. 0 suggests no bound

    normalize_obs: True
    normalize_reward: True

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 3e-4
    clip_norm: .5
    # arguments for loss
    clip_range: .2          # clip range for ppo
    entropy_coef: .0
    value_coef: 1

buffer:
    adv_type: gae     # nae or gae
    precision: *prec
    gamma: .99
    lam: .95
    n_envs: *nenvs
    N_STEPS: *nsteps
    N_MBS: *nmbs        # number of minibatches
    # mini-batch size = n_workers * n_envs * epslen / n_mbs
