---
env:
    name: &env_name BipedalWalker-v2 # LunarLanderContinuous-v2, BipedalWalker-v2
    video_path: video
    # max_episode_steps: 1000
    log_video: False
    n_workers: 1
    n_envs: 16
    seed: 0

model:
    shared_mlp_units: [128]
    use_dnc: False
    lstm_units: 128
    actor_units: [64]
    critic_units: [64]
    norm: none
    activation: relu

agent:
    algorithm: &algo ppo
    env_name: *env_name

    n_minibatches: 8        # number of minibatches a sequence is divided into 
    # batch size = n_workers * n_envs * seq_len / n_minibatches
    n_updates: 4            # number of updates per epoch
    n_epochs: 1000
    max_kl: .01              # early stop when max_kl is violated. 0 suggests no bound

    # model path: model_root_dir/model_name
    # tensorboard path: log_root_dir/model_name
    model_root_dir: saved_models            # root path for savinng models
    log_root_dir: logs      # root path for tensorboard logs
    model_name: *algo
    
    # arguments for optimizer
    optimizer: adam
    learning_rate: 3.e-4
    epsilon: 1.e-5
    clip_norm: .5
    # arguments for ppo loss
    clip_range: .2          # clip range for ppo
    entropy_coef: .0
    kl_coef: .1
    value_coef: .5

buffer:
    advantage_type: gae     # nae or gae
    gamma: .99
    lam: .95
    # environment hack
    # reward_scale: 5.
    # reward_clip: 50