---
env:
    name: &env_name LunarLander-v2
    n_workers: 1
    n_envs: 32
    seed: 0
    precision: &prec 32

model:
    cnn_name: none
    actor_units: [128, 64]
    critic_units: [128, 64]
    norm: none
    activation: relu
    init_std: .1

agent:
    algorithm: &algo ppo
    precision: *prec

    MAX_STEPS: 5.e+6
    N_STEPS: &nsteps 256
    N_UPDATES: 8
    N_MBS: &nmbs 4
    LOG_INTERVAL: 10000
    max_kl: .1            # early stop when max_kl is violated. 0 suggests no bound

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 1.e-3
    clip_norm: .5
    # arguments for loss
    clip_range: .2          # clip range for ppo
    entropy_coef: .0
    value_coef: .5

buffer:
    adv_type: gae     # nae or gae
    gamma: .99
    lam: .95
    n_steps: *nsteps
    n_mbs: *nmbs        # number of minibatches
    # mini-batch size = n_workers * n_envs * epslen / n_minibatches
    # environment hack
    # reward_scale: 5.
    # reward_clip: 50