---
env:
    name: procgen_miner
    distribution_mode: easy
    frame_skip: 1
    n_envs: &ne 64
    frame_stack: 1
    np_obs: True
    reward_scale: 1
    reward_clip: 10

model:
    encoder:
        cnn_name: impala
    # rnn:
    #     units: 512
    q:
        units_list: [512]
        layer_type: dense
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu
        duel: False
    additional_rnn_input: False

agent:
    algorithm: &algo rdqn
    replay_type: &replay seqper
    gamma: 0.99
    lambda: .95
    batch_size: &bs 32
    precision: 16

    schedule_act_eps: True
    act_eps_type: apex
    act_eps: .3
    eval_act_eps: 0

    store_state: False
    burn_in: False
    sample_size: &ss 16
    burn_in_size: &bis 0

    MAX_STEPS: 2.5e7          # maximum env steps
    TRAIN_PERIOD: 1
    EVAL_PERIOD: 2.5e5
    LOG_PERIOD: 2.5e5
    N_UPDATES: 1
    RECORD: True
    N_EVAL_EPISODES: 200

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: mse   # huber or mse
    target_update_period: 1500
    tbo: False                              # transformed Bellman Operator
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 2.5e-4
    epsilon: 1e-7

    # arguments for PER
    per_alpha: .9
    per_eta: .9
    per_epsilon: 1e-4
    use_is_ratio: &is False

replay:
    replay_type: *replay
    # arguments for PER
    beta0: .5
    to_update_top_priority: False
    use_is_ratio: *is

    # arguments for sequential replay
    batch_size: *bs
    sample_size: *ss
    burn_in_size: *bis
    min_size: 100
    capacity: 10000
    state_keys: ['h', 'c']
    extra_keys: ['obs', 'action', 'prob', 'mask']
