---
env:
    name: &env_name procgen_coinrun
    n_workers: 1
    n_envs: &nenvs 64
    frame_skip: 1
    frame_stack: 1
    np_obs: True
    gray_scale: False

model:
    encoder: 
        cnn_name: impala
    actor:
        units_list: []
        layer_type: dense
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu
    value:
        units_list: []
        layer_type: dense
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu

agent:
    algorithm: &algo ppo
    precision: 32
    gamma: &gamma .99

    MAX_STEPS: 2.5e7
    N_STEPS: &nsteps 256
    N_EPOCHS: 3
    N_MBS: &nmbs 8
    LOG_PERIOD: 100
    EVAL_PERIOD: 5000
    max_kl: 0            # early stop when max_kl is violated. 0 or null suggests unbound
    

    normalize_obs: False
    normalize_reward: True
    # (once, reuse, null)
    # "once" updates values at the end of each epoch
    # "reuse" updates values using value from learn, which is staler than once
    # null doesn't update values.
    value_update: null

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    RECORD: True
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 5e-4
    clip_norm: 0.5
    opt_eps: 1e-8
    # arguments for loss
    clip_range: .2          # clip range for ppo
    entropy_coef: &klcoef .01
    value_coef: 1.

buffer:
    adv_type: gae     # nae or gae
    gamma: *gamma
    lam: .95
    n_envs: *nenvs
    N_STEPS: *nsteps
    N_MBS: *nmbs        # number of minibatches
    kl_coef: *klcoef
    # mini-batch size = n_workers * n_envs * epslen / n_mbs
