---
algorithm: &algo mappo2
name: mappo2
precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
    algorithm: *algo
    MAX_STEPS: 1e8
    n_steps: &nsteps 400
    LOG_PERIOD: 200

env:
    env_name: &env_name smac2-3s5z_vs_3s6z
    n_runners: &nrunners 16
    n_envs: &nenvs 1
    use_state_agent: True
    use_mustalive: True
    add_center_xy: True
    timeout_done: True
    add_agent_id: False
    do_evaluation: False

agent: {}

strategy:
    train_loop:
        n_epochs: &nepochs 5
        N_VALUE_EPOCHS: &nval_epochs 0
        n_mbs: &nmbs 1
        max_kl: 0            # early stop when max_kl is violated. 0 or null suggests unbound

        # (once, reuse, null)
        # "once" updates values at the end of each epoch
        # "reuse" updates values using value from train, which is staler than once
        # null doesn't update values.
        value_update: null

model:
    rnn_type: &rnn rnn_mlstm

    policy:
        encoder: 
            nn_id: mlp
            units_list: [64, 64, 64]
            kernel_initializer: orthogonal
            activation: relu
            norm: layer
            norm_after_activation: True
            norm_kwargs:
                epsilon: 1.e-5
        rnn:
            nn_id: *rnn
            units: 64
            kernel_initializer: orthogonal
            use_ln: True
        policy:
            nn_id: policy
            units_list: []
            kernel_initializer: orthogonal
            eval_act_temp: 1
            attention_action: False
            embed_dim: 32
            out_gain: .01

    value:
        encoder:
            nn_id: mlp
            units_list: [64, 64, 64]
            kernel_initializer: orthogonal
            activation: relu
            norm: layer
            norm_after_activation: True
            norm_kwargs:
                epsilon: 1.e-5
        rnn:
            nn_id: *rnn
            units: 64
            kernel_initializer: orthogonal
            use_ln: True
        value:
            nn_id: value
            units_list: []
            kernel_initializer: orthogonal
            activation: relu

loss:
    policy:
        ppo_clip_range: .2
        entropy_coef: .01
        life_mask: True
    value:
        value_loss: clip
        value_clip_range: .2
        value_coef: 1
        life_mask: False

trainer:
    sample_size: &ss 10         # BPTT length
    store_state: True
    policy:
        optimizer:
            opt_name: adam
            schedule_lr: False
            lr: 5e-4
            clip_norm: 10
            epsilon: 1.e-5
            weight_decay: 0
    value:
        optimizer:
            opt_name: adam
            schedule_lr: False
            lr: 5e-4
            clip_norm: 10
            epsilon: 1.e-5

actor:
    rms:
        gamma: &gamma .99
        obs_names: [obs, global_state]
        normalize_obs: True
        normalize_reward: True
        update_reward_rms_in_time: False

buffer:
    type: mappo
    # dir: data/gd-100000
    use_dataset: False

    adv_type: gae     # nae or gae
    gamma: *gamma
    lam: .95
    n_runners: *nrunners
    n_envs: *nenvs
    n_steps: *nsteps
    n_epochs: *nepochs
    n_mbs: *nmbs        # number of minibatches
    sample_size: *ss
    norm_adv: minibatch
    # mini-batch size = n_runners * n_envs * epslen / n_mbs
    sample_keys: 
        - obs
        - global_state
        - action
        - value
        - traj_ret
        - advantage
        - logpi
        - mask
        - action_mask
        - life_mask
        - actor_h
        - actor_c
        - value_h
        - value_c
