---
env:
    name: atari_pong
    sticky_actions: False
    frame_stack: 4
    np_obs: True
    n_envs: 1
    seed: 0
model:
    cnn_name: impala
    kernel_initializer: glorot_uniform
    units_list: [512]
    activation: relu
    layer_type: dense
    duel: True
agent:
    algorithm: &algo asap-dqn
    replay_type: &replay per
    gamma: &gamma 0.99
    n_steps: &nsteps 3      # n-step target
    precision: &prec 32
    schedule_act_eps: True
    act_eps: 0  # will be overwritten in func.py
    
    # timer&interval
    MAX_STEPS: 1e9
    LOG_PERIOD: &log 1000
    N_UPDATES: *log

    # distributed algo params
    n_workers: 4
    SYNC_PERIOD: 1000

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: huber                          # huber or mse
    target_update_period: 2500
    tbo: True

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 1e-4
    clip_norm: 40
    opt_eps: 1.5e-4

    # arguments for PER
    per_alpha: .5
    per_epsilon: 1e-4

replay:
    replay_type: *replay
    seqlen: 100
    precision: 32
    # arguments for PER
    beta0: 0.4
    to_update_top_priority: False

    # arguments for general replay
    n_steps: *nsteps
    gamma: *gamma
    batch_size: 64
    min_size: 5e4
    capacity: 1e5
    has_next_obs: True
