---
env:
    name: BipedalWalkerHardcore-v3
    n_envs: 4
    seed: 0
    reward_clip: 10
model:
    actor:
        units_list: [512, 256, 128]
        kernel_initializer: orthogonal
        out_gain: .01
        norm: null
        activation: relu
        LOG_STD_MIN: -20
        LOG_STD_MAX: 2
    q:
        units_list: [512, 512, 256]
        # kernel_initializer: glorot_uniform
        norm: null
        activation: relu
    temperature:
        temp_type: constant
        value: .01
agent:
    algorithm: &algo asap-sac
    replay_type: &replay per
    gamma: &gamma .995
    batch_size: &bs 512
    n_steps: &nsteps 3      # n-step target
    polyak: .995
    evaluation: False
    
    # timer&interval
    MAX_STEPS: 2e7
    LOG_PERIOD: &log 60
    N_UPDATES: *log
    SYNC_PERIOD: 1000
    RECORD_PERIOD: False
    N_EVALUATION: 10

    schedule_act_eps: True
    act_eps_type: apex
    act_eps: .3
    eval_act_eps: 0
    schedule_act_temp: True
    n_exploit_envs: 2
    min_temp: .5
    max_temp: 2

    record_envs: 2

    # distributed algo params
    n_learner_cpus: 1
    n_learner_gpus: .3
    n_workers: 5
    n_worker_cpus: 1
    n_worker_gpus: .1
    run_mode: traj
    worker_side_prioritization: False

    # SAP params
    n_eval_envs: 1
    REPO_CAP: 10
    MIN_EVOLVE_MODELS: 2
    MAX_EVOLVE_MODELS: 10
    MIN_LEARN_PROB: .5
    MIN_EVOLVE_PROB: .3
    EVOLVE_LEARN_PROB: 0  # probability to further average evolved weights with the learned parameter
    REEVAL_PROB: .05
    FIFO: False
    WA_SELECTION: False
    WA_EVOLUTION: False
    fitness_method: norm
    mode_polyak: 0
    cb_c: .1    # coefficient for confidence bound method

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: mse                          # huber or mse

    # arguments for optimizer
    opt_name: adam
    schedule_lr: False
    actor_lr: 1e-4
    value_lr: 1e-4
    temp_lr: 1e-4
    # clip_norm: 10
    
    # arguments for PER
    per_alpha: 0.5
    per_epsilon: 1.e-4

buffer:
    replay_type: *replay
    seqlen: 50
    # arguments for PER
    beta0: 0.4
    beta_steps: 5e4
    to_update_top_priority: False

    # arguments for dual replay
    cap_frac: .25
    bs_frac: .5

    # arguments for general replay
    n_steps: *nsteps
    gamma: *gamma
    batch_size: *bs
    min_size: 5e4
    capacity: 1e6
    has_next_obs: True
