---
env:
    name: &env_name atari_pong
    n_workers: 1
    n_envs: &nenvs 8
    seed: 0
    precision: &prec 32
    wrapper: baselines
    frame_stack: 1
    
model:
    cnn_name: ftw
    shared_mlp_units: []
    lstm_units: 256
    actor_units: [256]
    critic_units: [256]
    norm: none
    kernel_initializer: orthogonal
    activation: relu
    init_std: 1

agent:
    algorithm: &algo ppo2
    precision: *prec

    MAX_STEPS: 5.e+7
    N_STEPS: &nsteps 128
    N_UPDATES: 4
    N_MBS: &nmbs 4
    sample_size: &ss 16       # BPTT length
    
    LOG_PERIOD: 200000
    max_kl: .1            # early stop when max_kl is violated. 0 suggests no bound

    normalize_obs: False
    normalize_reward: True
    store_state: True
    
    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 3.e-4
    clip_norm: .5
    # arguments for loss
    clip_range: .2          # clip range for ppo
    entropy_coef: .01
    value_coef: .5

buffer:
    adv_type: gae           # nae or gae
    precision: *prec
    gamma: .99
    lam: .95
    n_envs: *nenvs
    N_STEPS: *nsteps
    N_MBS: *nmbs
    sample_size: *ss
    # mini-batch size = n_workers * n_envs * epslen / n_mbs
