---
env:
    name: &env_name BipedalWalker-v3
    video_path: video
    log_video: False
    n_workers: 1
    n_envs: 16
    seed: 0
    precision: &prec 32
    # max_episode_steps: 27000    # 108000 frames / 4 frame-skips
    # is_deepmind_env: True

model:
    cnn_name: none
    shared_mlp_units: [128]
    use_dnc: False
    lstm_units: 64
    actor_units: [64]
    critic_units: [64]
    norm: none
    activation: relu
    init_std: .1

agent:
    algorithm: &algo ppo2
    precision: *prec

    MAX_STEPS: 5.e+6
    N_UPDATES: 8            # number of updates per epoch
    LOG_INTERVAL: 10000
    N_STEPS: 400
    max_kl: .05            # early stop when max_kl is violated. 0 suggests no bound

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    learning_rate: 3.e-4
    epsilon: 1.e-8
    clip_norm: .5
    # arguments for loss
    clip_range: .2          # clip range for ppo
    entropy_coef: .0
    kl_coef: .0
    value_coef: .001

buffer:
    advantage_type: gae     # nae or gae
    gamma: .99
    lam: .95
    n_minibatches: 1        # number of minibatches a sequence is divided into 
    min_transitions: 2000
    # mini-batch size = n_workers * n_envs * epslen / n_minibatches
    # environment hack
    # reward_scale: 5.
    # reward_clip: 50