---
env:
    name: &env_name BipedalWalker-v2 # LunarLanderContinuous-v2, BipedalWalker-v2
    video_path: video
    # max_episode_steps: 1000
    log_video: False
    n_workers: 8
    n_envs: 8
    seed: 0

model:
    shared_mlp_units: [128]
    use_dnc: False
    lstm_units: 128
    actor_units: [64]
    critic_units: [64]
    norm: none
    activation: relu

agent:
    algorithm: &algo ppo2
    env_name: *env_name

    learn_freq: 200         # learning interval, measured in steps
    # batch size = n_workers * n_envs * learn_freq
    n_updates: 8            # number of updates per epoch
    n_epochs: 1000
    max_kl: .0             # early stop when max_kl is violated. 0 suggests no bound

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: agent
    
    # arguments for optimizer
    optimizer: adam
    learning_rate: 1.e-4
    epsilon: 1.e-5
    clip_norm: .5
    # arguments for loss
    clip_range: .2          # clip range for ppo
    entropy_coef: .0
    kl_coef: .0
    value_coef: .5

buffer:
    advantage_type: gae     # nae or gae
    gamma: .99
    lam: .95
    # environment hack
    # reward_scale: 5.
    # reward_clip: 50