---
env:
    name: &env_name BipedalWalker-v3
    n_workers: 1
    n_envs: &nenvs 8
    seed: 0

model:
    encoder: 
        units_list: [64]
        kernel_initializer: glorot_uniform
        activation: relu
    rnn:
        lstm_units: 64
        lstm_ln: False
    actor:
        units_list: [64]
        init_std: 1
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu
    critic:
        units_list: [64]
        norm: null
        kernel_initializer: glorot_uniform
        activation: relu

agent:
    algorithm: &algo ppo2
    precision: &prec 32

    MAX_STEPS: 5e7
    N_STEPS: &nsteps 256
    N_UPDATES: 2
    N_MBS: &nmbs 4
    sample_size: &ss 16       # BPTT length
    LOG_PERIOD: 100
    EVAL_PERIOD: 1000
    max_kl: .1            # early stop when max_kl is violated. 0 or null suggests unbound

    normalize_obs: True
    normalize_reward: True
    store_state: True
    
    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    RECORD: False
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 3e-4
    clip_norm: .5
    # arguments for loss
    clip_range: .2          # clip range for ppo
    entropy_coef: .0
    value_coef: .001

buffer:
    adv_type: gae           # nae or gae
    precision: *prec
    gamma: .99
    lam: .95
    n_envs: *nenvs
    N_STEPS: *nsteps
    N_MBS: *nmbs
    sample_size: *ss
    shuffle: True
    # mini-batch size = n_workers * n_envs * epslen / n_mbs
