---
env:
    # is_deepmind_env: True
    name: &env_name BipedalWalker-v3
    video_path: video
    log_video: False
    n_workers: 1
    n_envs: 16
    # max_episode_steps: 27000    # 108000 frames / 4 frame-skips
    seed: 0
    episode_life: False

model:
    cnn_name: none
    shared_mlp_units: [256]
    use_dnc: False
    lstm_units: 128
    actor_units: [128]
    critic_units: [128]
    norm: none
    activation: relu

agent:
    algorithm: &algo ppo2
    env_name: *env_name

    LEARN_FREQ: 100         # learning interval, measured in steps
    # batch size = n_workers * n_envs * learn_freq
    n_updates: 8            # number of updates per step
    N_EPOCHS: 200000
    # max_kl: .1             # early stop when max_kl is violated. 0 suggests no bound
    LOG_INTERVAL: 10

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: True
    learning_rate: 3.e-4
    epsilon: 1.e-5
    clip_norm: 10
    # arguments for loss
    clip_range: .2          # clip range for ppo
    entropy_coef: .0
    kl_coef: .0
    value_coef: .01

buffer:
    advantage_type: gae     # nae or gae
    gamma: .99
    lam: .95
    min_transitions: 800      # the minimum number of transitions for learning
    # environment hack
    # reward_scale: 5.
    # reward_clip: 50