---
env:
    name: &env_name LunarLander-v2
    video_path: video
    log_video: False
    n_workers: 1
    n_envs: &nenvs 16
    seed: 0
    precision: &prec 32
model:
    cnn_name: none
    shared_mlp_units: [64]
    use_dnc: False
    lstm_units: 64
    actor_units: [64]
    critic_units: [64]
    norm: none
    activation: relu
    init_std: .1

agent:
    algorithm: &algo ppo
    precision: *prec

    MAX_STEPS: 5.e+6
    N_UPDATES: 4            # number of updates per epoch
    LOG_INTERVAL: 10000
    N_MBS: &mbs 4
    max_kl: .05            # early stop when max_kl is violated. 0 suggests no bound

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    learning_rate: 1.e-3
    epsilon: 1.e-8
    clip_norm: .5
    # arguments for loss
    clip_range: .2          # clip range for ppo
    entropy_coef: .0
    value_coef: .001

buffer:
    adv_type: gae     # nae or gae
    gamma: .99
    lam: .95
    n_envs: *nenvs
    n_mbs: *mbs        # number of minibatches
    # mini-batch size = n_workers * n_envs * epslen / n_minibatches
    # environment hack
    # reward_scale: 5.
    # reward_clip: 50