---
env:
    name: LunarLanderContinuous-v2
    video_path: video
    seed: 0
model:
    actor:
        units_list: [128, 64]
        kernel_initializer: glorot_uniform
        norm: none
        activation: relu
        LOG_STD_MIN: -20
        LOG_STD_MAX: 2
    q:
        units_list: [128, 64]
        kernel_initializer: glorot_uniform
        norm: none
        activation: relu
    temperature:
        temp_type: 'variable'
        value: .2
agent:
    algorithm: &algo sac
    precision: 32
    gamma: &gamma 0.99
    polyak: .995
    # act_eps: .3
    target_entropy: .1                      # tune this param for discrete actions
    
    MAX_STEPS: 3.e+6
    LOG_INTERVAL: 10000

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: mse                          # huber or mse
    tbo: False                               # transformed Bellman Operator

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    actor_lr: 3.e-4
    q_lr: 3.e-4
    temp_lr: 3.e-4
    
    # arguments for PER
    per_alpha: 0.5
    per_epsilon: 1.e-4

replay:
    type: uniform                      # proportional or uniform
    # arguments for PER
    beta0: 0.4
    beta_steps: 5.e+4
    to_update_top_priority: True

    # hacking
    # normalize_reward: False
    # reward_scale: 1

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: 100
    min_size: 1.e+4
    capacity: 1.e+6
    has_next_obs: False
