---
env:
    name: HalfCheetah-v3
    video_path: video
    log_video: False
    seed: 0

model:
    actor:
        units_list: [256, 256]
        kernel_initializer: glorot_uniform
        # norm: layer
        # activation: relu
    q:
        units_list: [256, 256]
        kernel_initializer: glorot_uniform
        # norm: layer
        # activation: relu
    temperature:
        temp_type: 'constant'
        value: .2
agent:
    algorithm: &algo sac
    gamma: &gamma 0.99
    polyak: .995
    # target_entropy: -4                      # this should be set to be some small positive value for discrete environment, e.g. 0.01
    
    MAX_STEPS: 3.e+6
    TIME_INTERVAL: 100
    timer: False

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: mse                          # huber or mse
    tbo: False                               # transformed Bellman Operator

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    actor_lr: 1.e-3
    q_lr: 1.e-3
    temp_lr: 1.e-3
    epsilon: 1.e-8

    # arguments for PER
    # per_alpha: 0.5
    # per_epsilon: 1.e-4

replay:
    type: uniform                      # proportional or uniform
    # arguments for PER
    # beta0: 0.4
    # beta_steps: 5e4
    # to_update_top_priority: True

    # hacking
    # normalize_reward: False
    # reward_scale: 1

    # arguments for general replay
    n_steps: 1
    gamma: *gamma
    batch_size: 100
    min_size: 1e3
    capacity: 1e6
    has_next_state: False
