---
algorithm: &algo zero
name: zero

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
    algorithm: *algo

    MAX_STEPS: 5e7
    n_steps: &nsteps 50
    LOG_PERIOD: 1e5
    EVAL_PERIOD: null

    RECORD_VIDEO: False
    N_EVAL_EPISODES: 1
    size: [256, 256]

env:
    env_name: &env_name overcooked-asymmetric_advantages
    n_runners: &nrunners 10
    n_envs: &nenvs 4
    max_episode_steps: 400
    dense_reward: True
    featurize: True

    uid2aid: [0, 1]

agent: {}

monitor:
    use_tensorboard: True

strategy:
    algorithm: *algo
    train_loop: {}

model:
    aid: 0
    rnn_type: &rnn null
    gamma: &gamma .99

    encoder: 
        nn_id: null
    rnn:
        nn_id: *rnn
    policy:
        nn_id: policy
        units_list: [256, 256, 256]
        w_init: orthogonal
        activation: relu
        norm: null
        out_scale: .01
        index: null
        index_config:
            use_shared_bias: False
            use_bias: True
            w_init: orthogonal
    value:
        nn_id: value
        units_list: [256, 256, 256]
        w_init: orthogonal
        activation: relu
        norm: null
        index: null
        index_config:
            use_shared_bias: False
            use_bias: True
            w_init: orthogonal

loss:
    # hyperparams for value target and advantage
    target_type: gae
    c_clip: 1
    rho_clip: 1
    adv_type: vtrace
    norm_adv: False

    # hyperparams for policy optimization
    pg_type: ppo
    ppo_clip_range: .05
    kl: reverse
    kl_coef: 1
    policy_life_mask: True

    # hyperparams for value learning
    value_loss: mse
    value_clip_range: .2
    value_life_mask: False

    stats:
        gamma: *gamma
        lam: .95
        pg_coef: 1
        entropy_coef: .01
        value_coef: .5

trainer:
    algorithm: *algo
    aid: 0
    n_runners: *nrunners
    n_envs: *nenvs
    n_epochs: &nepochs 4
    n_mbs: &nmbs 1
    n_steps: *nsteps         # BPTT length
    timeout_done: &td True

    theta_opt:
        opt_name: adam
        lr: 5e-4
        clip_norm: .1
        eps: 1e-5

actor:
    update_obs_rms_at_execution: False
    update_obs_at_execution: False
    rms:
        obs_names: [obs]
        obs_normalized_axis: [0, 1, 2]
        reward_normalized_axis: [0, 1, 2]
        normalize_obs: False
        obs_clip: 10
        normalize_reward: False
        update_reward_rms_in_time: False
        gamma: *gamma

buffer:
    type: ac

    n_runners: *nrunners
    n_envs: *nenvs
    n_steps: *nsteps
    queue_size: 2
    timeout_done: *td
    rnn_type: *rnn

    sample_keys: 
        - obs
        - action
        - value
        - reward
        - discount
        - reset
        - mu_logprob
        - mu
        - mask
        - h
        - c
