---
env:
    name: BipedalWalker-v2
    video_path: video
    log_video: False
    seed: 0

model:
    actor:
        units_list: [512, 256]
        activation: relu
    q:
        units_list: [512, 256]
        activation: relu
    temperature:
        temp_type: 'state-action'
        value: .2
agent:
    algorithm: &algo sac
    gamma: &gamma 0.99
    polyak: .995                            # moving average rate
    sync_target: False
    target_update_freq: 100 
    # target_entropy: -4                      # this should be set to be some small positive value for discrete environment, e.g. 0.01
    TIME_INTERVAL: 100
    timer: False

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: mse                          # huber or mse
    tbo: False                               # transformed Bellman Operator
    max_steps: 3.e+6

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    actor_lr: 1.e-4
    q_lr: 3.e-4
    temp_lr: 1.e-4
    epsilon: 1.e-5

    # arguments for PER
    per_alpha: 0.5
    per_epsilon: 1.e-4

replay:
    type: proportional                      # proportional or uniform
    # arguments for PER
    beta0: 0.4
    beta_steps: 5e4
    to_update_top_priority: False

    # hacking
    normalize_reward: False
    reward_scale: 1

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: 256
    min_size: 5e3
    capacity: 1e6
