---
env:
    name: atari_breakout
    wrapper: baselines
    sticky_actions: True
    seed: 0

model:
    cnn: ftw
    lstm_units: 512
    v_units: [512]
    a_units: [512]
    activation: relu
    duel: False

agent:
    algorithm: &algo r2d2
    gamma: 0.99
    lambda: .95
    precision: &prec 16
    batch_size: &bs 64

    store_state: True
    burn_in: True
    sample_size: &ss 80
    burn_in_size: &bis 40
    schedule_eps: True
    add_input: False
    act_eps: 0

    MAX_STEPS: 1e9
    LOG_PERIOD: &log 1000
    N_UPDATES: *log
    
    # distributed algo params
    n_workers: 6
    SYNC_PERIOD: 1500

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: mse                          # huber or mse
    target_update_period: 1500
    tbo: False

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 1e-4
    clip_norm: 40

    # arguments for PER
    per_alpha: 0.4
    per_eta: .9
    per_epsilon: 1e-4

replay:
    type: sper                      # per or uniform
    precision: *prec
    # arguments for PER
    beta0: 0
    to_update_top_priority: False

    # arguments for general replay
    batch_size: *bs
    sample_size: *ss
    burn_in_size: *bis
    min_size: 500
    capacity: 10000
