---
algorithm: &algo dreamer
name: dreamer
info: dreamer

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
    algorithm: *algo

    MAX_STEPS: 1e8
    n_steps: &nsteps 100
    LOG_PERIOD: 2e5

    n_envs: &nenvs 32 # 64
    n_recent_trajectories: 16
    rollout_length: 10

env:
    env_name: &env_name magw-escalation
    n_runners: &nrunners 1
    n_envs: *nenvs
    max_episode_steps: 50
    reward_scale: .1
    population_size: 1
    timeout_done: &td False

    uid2aid: [0, 1]

agent: {}

monitor:
    use_tensorboard: True

strategy:
    algorithm: *algo
    train_loop: {}

model:
    aid: 0
    n_elites: 1
    global_state_type: concat
    rn_std: .1
    stoch_size: 32
    deter_size: 64
    rssm_rnn_type: &rrnn gru

    gamma: &gamma .99

    reprelayer:
        nn_id: reprelayer
        norm: null
        repre_units_list: [64, 64]
    embedlayer:
        nn_id: embedlayer 
        norm: null
        embed_units_list: [64, 64]
    rssmrnnlayer:
        nn_id: rssmrnnlayer
        rnn_type: *rrnn
        rnn_units: 64
    translayer:
        nn_id: translayer
        norm: null
        trans_units_list: [64, 64]
    reward:
        nn_id: reward
        out_size: 1
        units_list: [32, 32]
        activation: relu
        out_scale: .01
    discount:
        nn_id: discount
        out_size: 1
        units_list: [32, 32]
        activation: relu
    stateencoder:
        nn_id: stateencoder
        out_size: 1
        units_list: [32, 32]
        activation: relu
        out_scale: .01
    obsencoder:
        nn_id: obsencoder
        out_size: 1
        units_list: [32, 32]
        activation: relu
    decoder:
        nn_id: decoder
        out_size: 1
        units_list: [32, 32]
        activation: relu
    policy:
        nn_id: policy
        units_list: [64, 64]
        w_init: orthogonal
        activation: tanh
        norm: null
        out_scale: .01
        rnn_type: &prnn gru
        rnn_units: 64
    value:
        nn_id: value
        units_list: [64, 64]
        w_init: orthogonal
        activation: tanh
        norm: null
        rnn_type: &vrnn gru
        rnn_units: 64


loss:
    # hyperparams for value target and advantage
    target_type: gae
    c_clip: 1
    rho_clip: 1
    adv_type: vtrace
    norm_adv: True

    prnn_bptt: 10
    vrnn_bptt: 10

    # hyperparams for policy optimization
    pg_type: ppo
    ppo_clip_range: .2
    reg_type: kl_reverse
    reg_coef: 0
    policy_sample_mask: True

    # hyperparams for value learning
    value_loss: mse
    value_clip_range: .2
    value_sample_mask: False

    stats:
        gamma: *gamma
        lam: &lam .95
        pg_coef: 1
        entropy_coef: .01
        value_coef: 1

    model_loss_type: discrete
    reconstruction_loss_type: mse
    vrnn: *vrnn

    rssm_coef: 1
    reg_coef: 1
    recons_coef: 1
    model_coef: 1
    reward_coef: 1
    discount_coef: 1

trainer:
    algorithm: *algo
    aid: 0
    n_runners: *nrunners
    n_envs: *nenvs
    n_epochs: &nepochs 50
    timeout_done: *td

    rl_opt:
        opt_name: adam
        lr: 5e-4
        clip_norm: null
        eps: 1e-5

    model_opt:
        opt_name: adam
        lr: 5e-4
        clip_norm: null
        eps: 1e-5

actor: {}


buffer:
    type: ac

    n_runners: *nrunners
    n_envs: *nenvs
    n_simulated_envs: 4
    n_steps: 10
    batch_size: 16 # 128

    auto_state: False

    sample_keys: 
        - obs
        - action
        - reward
        - discount
        - reset
