---
env:
    name: procgen_coinrun
    frame_skip: 2
    gray_scale: True
    frame_stack: 4

model:
    cnn: impala
    cnn_out_size: null
    kernel_initializer: orthogonal
    units_list: [512]
    activation: relu
    layer_type: dense
    duel: False

    tau_embed_size: 64
    phi_activation: relu
    K: &K 32

agent:
    algorithm: &algo iqn
    replay_type: &replay 'uniform'
    batch_size: &bs 32
    gamma: &gamma 0.99
    n_steps: &nsteps 1      # n-step target
    precision: &prec 32
    schedule_act_eps: True
    act_eps: 0.01
    eval_act_eps: 0

    MAX_STEPS: 8e6      # maximum env frames
    TRAIN_PERIOD: 128    # #frames
    EVAL_PERIOD: 5e5
    LOG_PERIOD: 1e4
    N_UPDATES: 1
    RECORD: True

    # IQN params
    N: 8                # N in paper, num of quantiles for online quantile network
    N_PRIME: 8          # N' in paper, num of quantiles for target quantile network
    K: *K               # K in paper, num of quantiles for action selection
    KAPPA: 1            # 𝜅 in paper, used as the threshold for the huber loss

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    target_update_period: 2000  # trainning step
    tbo: False                              # transformed Bellman Operator
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 5e-5
    clip_norm: 0
    epsilon: 1.5e-4

    # arguments for PER
    per_alpha: .4
    per_epsilon: 1e-4

replay:
    replay_type: *replay
    precision: 32
    # arguments for PER
    beta0: 0
    to_update_top_priority: True

    # arguments for general replay
    n_steps: *nsteps
    gamma: *gamma
    batch_size: *bs
    min_size: 5e4
    capacity: 1e5
    has_next_obs: False
