---
algorithm: &algo happo_lka2
name: happo_lka2
info: happo_lka2

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
    algorithm: *algo

    MAX_STEPS: 1e7
    n_steps: &nsteps 64
    LOG_PERIOD: 1e5
    EVAL_PERIOD: null

    n_eval_envs: 1000
    RECORD_VIDEO: True
    N_EVAL_EPISODES: 1
    size: [256, 256]

    n_lookahead_steps: 1
    n_simulated_envs: &nse 640
    n_simulated_steps: &nss 10
    model_rollout_type: sim
    compute_return_at_once: True
    ignore_ratio_for_ego: False
    ignore_ratio_for_lookahead: False
    perm: null
    restore_state: False
    switch_model_at_every_step: False
    quantify_dynamics_errors: False
    rollout_type: part

    concise_mode: True

env:
    env_name: &env_name grf-11_vs_11_hard_stochastic
    representation: simple115v2
    rewards: scoring,checkpoints
    render: False
    write_full_episode_dumps: False
    write_video: False
    dump_frequency: 1000
    logdir: results/grf
    extra_players: null
    number_of_left_players_agent_controls: 11
    number_of_right_players_agent_controls: 0
    add_role_to_obs: False
    shared_ckpt_reward: False

    max_episode_steps: 200
    use_action_mask: False
    uid2aid: null
    share_policy: False

    n_runners: &nrunners 1
    n_envs: &nenvs 32

    use_idx: False
    use_hidden: False
    use_event: False
    agentwise_global_state: False
    timeout_done: &td False

agent: {}

monitor:
    use_tensorboard: True

strategy:
    algorithm: *algo
    train_loop: {}

model:
    aid: 0
    gamma: &gamma .99

    policy:
        nn_id: policy
        units_list: [256, 256, 256]
        w_init: orthogonal
        activation: relu
        norm: null
        out_scale: .01
        rnn_type: &prnn null
        rnn_units: 256
    value:
        nn_id: value
        units_list: [256, 256, 256]
        w_init: orthogonal
        activation: relu
        norm: null
        rnn_type: &vrnn null
        rnn_units: 256

loss:
    # hyperparams for value target and advantage
    target_type: gae
    c_clip: 1
    rho_clip: 1
    adv_type: gae
    norm_adv: True

    prnn_bptt: 64
    vrnn_bptt: 64

    lka_prnn_bptt: 64
    lka_vrnn_bptt: 64

    # hyperparams for policy optimization
    pg_type: ppo
    ppo_clip_range: .2
    kl_type: reverse
    kl_coef: 0
    pos_kl_coef: 0
    neg_kl_coef: 0
    policy_sample_mask: True

    # hyperparams for value learning
    value_loss: mse
    value_clip_range: .2
    value_sample_mask: False

    stats:
        gamma: *gamma
        lam: &lam .95
        pg_coef: 1
        entropy_coef: 5e-4
        value_coef: 1

trainer:
    algorithm: *algo
    aid: 0
    n_runners: *nrunners
    n_envs: *nenvs
    n_epochs: &nepochs 5
    n_mbs: &nmbs 1
    n_steps: *nsteps
    update_scheme: step

    n_simulated_envs: *nse
    n_simulated_steps: *nss
    n_lka_epochs: *nepochs
    n_lka_mbs: *nmbs

    theta_opt:
        opt_name: adam
        lr: 1e-4
        clip_norm: .5
        eps: 1e-5

actor:
    update_obs_rms_at_execution: False
    update_obs_at_execution: False
    rms:
        obs_names: [obs, global_state]
        obs_normalized_axis: [0, 1, 2]
        reward_normalized_axis: [0, 1, 2]
        normalize_obs: False
        obs_clip: 10
        normalize_reward: False
        update_reward_rms_in_time: False
        gamma: *gamma

buffer:
    type: ac

    n_runners: *nrunners
    n_envs: *nenvs
    n_steps: *nsteps
    queue_size: 2
    timeout_done: *td

    gamma: *gamma
    lam: *lam

    sample_keys: 
        - obs
        - global_state
        - action
        - value
        - reward
        - discount
        - reset
        - mu_logprob
        - mu_logits
        - state_reset
        - state
