---
algorithm: &algo zero
name: zero

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
    algorithm: *algo

    MAX_STEPS: 5e5
    n_steps: &nsteps 32
    LOG_PERIOD: 1e4
    EVAL_PERIOD: null

    RECORD_VIDEO: True
    N_EVAL_EPISODES: 1
    size: [256, 256]

env:
    env_name: &env_name matrix-ipd
    n_runners: &nrunners 1
    n_envs: &nenvs 8
    max_episode_steps: 150
    uid2aid: [0, 0]
    use_idx: True
    use_hidden: True

agent: {}

strategy:
    algorithm: *algo
    train_loop: {}

model:
    aid: 0
    rnn_type: &rnn null
    joint_theta_objective: &jto False
    joint_objective: &jo True
    rl_reward: &rlreward meta
    gamma: &gamma .99
    eval_act_temp: 1
    meta_reward_type: intrinsic
    K: &K 3
    L: &L 0
    extra_meta_step: &ems 1 # 0/1

    encoder: 
        nn_id: null
    rnn:
        nn_id: *rnn
        units: 64
        w_init: orthogonal
        recurrent_initializer: orthogonal
        use_ln: True
    policy:
        nn_id: policy
        units_list: []
        w_init: orthogonal
        activation: relu
        norm: null
        eval_act_temp: 1
        out_scale: .01
        index: all
        index_config:
            use_shared_bias: False
            use_bias: True
            w_init: orthogonal
    value:
        nn_id: value
        units_list: []
        w_init: orthogonal
        activation: relu
        norm: null
        index: all
        index_config:
            use_shared_bias: False
            use_bias: True
            w_init: orthogonal
    outer_value:
        nn_id: value
        units_list: []
        w_init: orthogonal
        activation: relu
        norm: null
        index: null
        index_config:
            use_shared_bias: False
            use_bias: True
            w_init: orthogonal
    meta_reward: 
        nn_id: reward
        units_list: []
        w_init: orthogonal
        activation: relu
        norm: null
        out_scale: .01
        combine_xa: False
        reward_size: 11
        reward_range: 1
        index: all
        index_config:
            use_shared_bias: False
            use_bias: True
            w_init: orthogonal
    meta_params:
        nn_id: meta
        pg_coef:
            outer: 1
            default: 1
            init: null
            act: sigmoid
        entropy_coef:
            outer: 5e-2
            default: 5e-2
            init: null
            act: sigmoid
        value_coef:
            outer: .5
            default: .5
            scale: 1
            bias: 0
            init: null
            act: sigmoid
        gamma: 
            outer: *gamma
            default: *gamma
            scale: 1
            bias: 0
            init: null
            act: sigmoid
        lam:
            outer: .95
            default: .95
            scale: 1
            bias: 0
            init: null
            act: sigmoid
        reward_scale:
            outer: 1
            default: 1
            scale: 1
            bias: 0
            init: null
            act: tanh
        reward_bias:
            outer: 0
            default: 0
            scale: 1
            bias: 0
            init: null
            act: null
        reward_coef:
            outer: 1
            default: 1
            scale: 1
            bias: 0
            init: null
            act: tanh

loss:
    # hyperparams for value target and advantage
    target_type: gae
    c_clip: 1
    rho_clip: 1
    adv_type: vtrace
    norm_adv: False
    norm_meta_adv: False

    # hyperparams for policy optimization
    pg_type: pg
    ppo_clip_range: .2
    use_dice: True
    dice_axis: null
    dice_lam: 1
    kl: reverse
    kl_coef: 1
    policy_life_mask: True
    joint_theta_objective: *jto

    # hyperparams for value learning
    value_loss: mse
    value_clip_range: .2
    value_life_mask: False
    stop_target_grads: True

    # hyperparams for meta-learning
    meta_reward_entropy_coef: 0
    meta_indicator_coef: 0
    joint_objective: *jo

trainer:
    algorithm: *algo
    aid: 0
    n_runners: *nrunners
    n_envs: *nenvs
    n_epochs: &nepochs 1
    n_mbs: &nmbs 1
    n_meta_epochs: 1
    n_steps: *nsteps         # BPTT length
    timeout_done: &td True
    K: *K
    L: *L
    msmg_type: last
    extra_meta_step: *ems
    store_state: True
    event_done: False
    
    theta_opt:
        opt_name: rmsprop
        lr: 1
    phi_opt:
        opt_name: rmsprop
        lr: 1
        clip_norm: 10
        eps: 1e-5
    meta_params_opt:
        opt_name: rmsprop
        lr: 1
        clip_norm: 10
        eps: 1e-5
    meta_reward_opt:
        opt_name: rmsprop
        lr: 1
        clip_norm: 10
        eps: 1e-5

actor:
    update_obs_rms_at_execution: False
    update_obs_at_execution: False
    rms:
        obs_names: [obs]
        obs_normalized_axis: [0, 1, 2]
        reward_normalized_axis: [0, 1, 2]
        normalize_obs: False
        obs_clip: 10
        normalize_reward: False
        update_reward_rms_in_time: False
        gamma: *gamma

buffer:
    type: ac

    n_runners: *nrunners
    n_envs: *nenvs
    n_steps: *nsteps
    queue_size: 2
    K: *K
    L: *L
    extra_meta_step: *ems
    timeout_done: *td
    rnn_type: *rnn

    sample_keys: 
        - obs
        - action
        - value
        - reward
        - discount
        - reset
        - mu_logprob
        - mu
        - mask
        - h
        - c
