---
env:
    name: atari_pong
    wrapper: my_atari
    life_done: False
    sticky_actions: True
    frame_stack: 4
    seed: 0

model:
    cnn: nature
    head_units: [256]
    activation: relu
    layer_type: dense
    duel: True

agent:
    algorithm: &algo dqn
    gamma: &gamma 0.99
    precision: &prec 32
    schedule_act_eps: True
    act_eps: 0

    MAX_STEPS: 1e9          # maximum training frames
    TRAIN_PERIOD: 16          # #frames = 4 agent step when frame skip = 4
    EVAL_PERIOD: 1e6
    LOG_PERIOD: 1e5
    N_UPDATES: 1

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: huber   # huber or mse
    target_update_period: 8000
    tbo: True                              # transformed Bellman Operator
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 1e-4
    clip_norm: 40
    epsilon: 1.5e-4

    # arguments for PER
    per_alpha: 0.5
    per_epsilon: 1e-4

replay:
    type: per      # uniform, per
    precision: *prec
    # arguments for PER
    beta0: 0
    to_update_top_priority: True

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: 64
    min_size: 8e4
    capacity: 1e6
    has_next_obs: True
