---
env:
    name: atari_pong
    wrapper: baselines
    precision: &prec 32
    life_done: True
    sticky_actions: True
    frame_stack: 4
    seed: 0
model:
    q:
        cnn: nature
        v_units: [256]
        a_units: [256]
        activation: relu
        layer_type: noisy
        duel: False
agent:
    algorithm: &algo dqn
    gamma: &gamma 0.99
    precision: *prec
    schedule_eps: False
    act_eps: 0

    MAX_STEPS: 1e9          # maximum training frames
    TRAIN_INTERVAL: 16          # #frames = 4 agent step when frame skip = 4
    EVAL_INTERVAL: 1e6
    LOG_INTERVAL: 1e5

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: huber   # huber or mse
    target_update_freq: 32000               # #frames = 8000 agent step when frame skip = 4
    tbo: False                              # transformed Bellman Operator
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 6.25e-5
    clip_norm: 10
    epsilon: 1.5e-4

    # arguments for PER
    per_alpha: 0.5
    per_epsilon: 1e-4

replay:
    type: proportional      # uniform, proportional
    precision: *prec
    # arguments for PER
    beta0: 0.4
    to_update_top_priority: True

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: 64
    min_size: 8e4
    capacity: 1e5
    has_nth_obs: True
