---
env:
    name: BipedalWalkerHardcore-v3
    n_envs: 1
    seed: 0
    reward_clip: 10
model:
    actor:
        units_list: [512, 256, 128]
        norm: none
        activation: relu
        LOG_STD_MIN: -20
        LOG_STD_MAX: 2
    q:
        units_list: [512, 512, 256]
        norm: none
        activation: relu
    temperature:
        temp_type: 'constant'
        value: .01
agent:
    algorithm: &algo apex-sac
    replay_type: &replay 'uniform'
    gamma: &gamma 0.99
    n_steps: &nsteps 3      # n-step target
    polyak: .995
    precision: &prec 32
    evaluation: False
    act_eps: 0
    
    # timer&interval
    MAX_STEPS: 1e8
    LOG_PERIOD: 1000

    # distributed algo params
    n_workers: 3

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: mse                          # huber or mse

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    actor_lr: 1e-4
    q_lr: 1e-4
    temp_lr: 1e-4
    # clip_norm: 10

    # arguments for PER
    per_alpha: 0.7
    per_epsilon: 1e-4

replay:
    replay_type: *replay
    seqlen: 0
    # arguments for PER
    beta0: 0.4
    beta_steps: 5e4
    to_update_top_priority: False

    # arguments for general replay
    n_steps: *nsteps
    gamma: *gamma
    batch_size: 512
    min_size: 5e4
    capacity: 1e6
    has_next_obs: False                 # should be true if workers send incomplete trajs

