---
env:
    name: atari_pong
    n_envs: 2
    seed: 0
model:
    q:
        cnn: nature
        v_units: [512]
        a_units: [512]
agent:
    algorithm: &algo apex-dqn
    gamma: &gamma 0.99
    
    # timer&interval
    MAX_STEPS: 1.e+7
    LOG_INTERVAL: 10000
    
    # distributed algo params
    n_workers: 4

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: agent

    loss_type: huber                          # huber or mse
    target_update_freq: 2500

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 6.25e-5
    clip_norm: 40
    epsilon: 1.e-4

    # arguments for PER
    per_alpha: 0.5
    per_epsilon: 1.e-4

replay:
    type: proportional                      # proportional or uniform
    # arguments for PER
    beta0: 0.4
    to_update_top_priority: False

    # hacking
    # reward_scale: 5
    # reward_clip: 50

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: 32
    min_size: 5e4
    capacity: 1e6
