---
env:
    name: atari_pong
    wrapper: baselines
    precision: &prec 32
    life_done: True
    sticky_actions: True
    frame_stack: 4
    n_envs: 1
    seed: 0
model:
    q:
        cnn: ftw
        v_units: [256]
        a_units: [256]
        activation: relu
        layer_type: noisy
        duel: False
agent:
    algorithm: &algo apex-d3qn
    gamma: &gamma 0.99
    precision: *prec
    schedule_eps: False
    act_eps: 0  # will be overwritten in func.py
    
    # timer&interval
    MAX_STEPS: 1e9
    LOG_INTERVAL: 10000
    
    # distributed algo params
    n_workers: 6
    actor_update_period: 1500

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: huber                          # huber or mse
    target_update_freq: 2500
    tbo: False

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 1e-4
    clip_norm: 40
    epsilon: 1.5e-4

    # arguments for PER
    per_alpha: 0.4
    per_epsilon: 1e-4

replay:
    type: proportional                      # proportional or uniform
    seqlen: 100
    precision: *prec
    # arguments for PER
    beta0: 0.4
    to_update_top_priority: False

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: 64
    min_size: 5e4
    capacity: 1e5
    has_nth_obs: True
