---
env:
    name: procgen_coinrun
    frame_skip: 2
    gray_scale: True
    frame_stack: 4
    np_obs: True

model:
    encoder:
        cnn: impala
        cnn_out_size: none
        kernel_initializer: orthogonal
    fpn:
        N: &N 32
        kernel_initializer: orthogonal
    iqn:
        kernel_initializer: orthogonal
        units_list: [512]
        activation: relu
        layer_type: dense
        duel: False

        tau_embed_size: 64
        phi_activation: relu

agent:
    algorithm: &algo apex-fqf
    replay_type: &replay 'uniform'
    batch_size: &bs 64
    gamma: &gamma 0.99
    n_steps: &nsteps 3      # n-step target
    precision: &prec 32
    schedule_act_eps: True
    act_eps: 0  # will be overwritten in func.py
    eval_act_eps: 0
    
    # timer&interval
    MAX_STEPS: 8e6
    LOG_PERIOD: &log 1000
    N_UPDATES: *log
    SYNC_PERIOD: 1000
    RECORD_PERIOD: 100
    N_EVALUATION: 10

    # IQN params
    N: *N                # N in paper, num of quantiles for online quantile network
    KAPPA: 1            # 𝜅 in paper, used as the threshold for the huber loss

    # distributed algo params
    n_learner_cpus: 3
    n_workers: 6

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    target_update_period: 1500
    tbo: False

    # arguments for optimizer
    iqn_opt: adam
    schedule_lr: False
    iqn_lr: 1e-4
    fpn_opt: rmsprop
    fpn_lr: 2.5e-9
    ent_coef: .1
    clip_norm: 0
    epsilon: 1.5e-4

    # arguments for PER
    per_alpha: .5
    per_epsilon: 1e-4

replay:
    replay_type: *replay
    seqlen: 100
    precision: 32
    # arguments for PER
    beta0: 0.4
    to_update_top_priority: False

    # arguments for general replay
    n_steps: *nsteps
    gamma: *gamma
    batch_size: *bs
    min_size: 5e4
    capacity: 1e5
    has_next_obs: True
