---
env:
    name: Walker2d-v3
    n_envs: 1
    seed: 0
    precision: &prec 32
model:
    actor:
        units_list: [256, 256]
        norm: null
        activation: relu
        LOG_STD_MIN: -20
        LOG_STD_MAX: 2
    q:
        units_list: [256, 256]
        norm: null
        activation: relu
    temperature:
        temp_type: 'variable'
        value: 1
agent:
    algorithm: &algo apex-sac
    replay_type: &replay 'uniform'
    gamma: &gamma .99
    n_steps: &nsteps 3      # n-step target
    polyak: .995
    precision: *prec
    schedule_act_eps: False
    act_eps: 0

    # timer&interval 
    MAX_STEPS: 3e6
    LOG_PERIOD: 10000
    timer: False

    # distributed algo params
    n_workers: 2

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    actor_lr: 3e-4
    q_lr: 3e-4
    temp_lr: 3e-4

    # arguments for PER
    per_alpha: .5
    per_epsilon: 1e-4

replay:
    replay_type: *replay
    seqlen: 0
    # arguments for PER
    beta0: .4
    beta_steps: 5e+4
    to_update_top_priority: True

    # arguments for general replay
    n_steps: *nsteps
    gamma: *gamma
    batch_size: 512
    min_size: 5e+4
    capacity: 1e+6
    has_next_obs: False                 # should be true if workers send incomplete trajs
