---
env:
    name: procgen_coinrun
    frame_skip: 2
    gray_scale: True
    frame_stack: 4
    np_obs: True

model:
    cnn: 
        cnn: impala
        cnn_out_size: none
        kernel_initializer: he_uniform
    actor:
        units_list: [512]
        activation: relu
    q:
        units_list: [512]
        activation: relu
        duel: False

        tau_embed_size: 64
        phi_activation: relu
        K: &K 32
    temperature:
        temp_type: 'variable'
        value: .1

agent:
    algorithm: &algo apex-sacd
    replay_type: &replay 'uniform'
    gamma: &gamma 0.99
    batch_size: &bs 64
    n_steps: &nsteps 3      # n-step target
    schedule_act_eps: False
    act_eps: 0
    eval_act_eps: 0
    target_entropy_coef: .5

    MAX_STEPS: 8e6      # maximum env steps
    LOG_PERIOD: &log 1000
    N_UPDATES: *log
    SYNC_PERIOD: 1000
    RECORD_PERIOD: 100
    N_EVALUATION: 10

    # distributed algo params
    n_learner_cpus: 3
    n_workers: 6

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    target_update_period: 1500

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    actor_lr: 3e-4
    q_lr: 3e-4
    temp_lr: 3e-4
    
    # arguments for PER
    per_alpha: .5
    per_epsilon: 1e-4

replay:
    replay_type: *replay
    seqlen: 100
    # arguments for PER
    beta0: 0.4
    beta_steps: 5e4
    to_update_top_priority: False

    # arguments for general replay
    n_steps: *nsteps
    gamma: *gamma
    batch_size: *bs
    min_size: 5e4
    capacity: 1e5
    has_next_obs: True
