---
env:
    name: procgen_chaser
    frame_skip: 1
    n_envs: &ne 4
    gray_scale: False
    frame_stack: 4
    np_obs: True
    reward_scale: 2
    reward_clip: 10

model:
    reward_entropy: False

agent:
    algorithm: &algo apex-sacdiqn
    replay_type: &replay per
    batch_size: &bs 64
    gamma: &gamma 0.99
    n_steps: &nsteps 3      # n-step target
    target_entropy_coef: .8
        # - [4.e+4, .8]
        # - [7.e+4, .3]
    worker_side_prioritization: False

    seq_act_eps: True
    schedule_act_temp: True
    eval_act_temp: .5
    n_exploit_envs: 8
    schedule_act_eps: True
    act_eps_type: apex
    act_eps: .3
    eval_act_eps: 0
    min_temp: .5
    max_temp: 10
    
    MAX_STEPS: 1e7      # maximum env steps
    LOG_PERIOD: 100
    N_UPDATES: 1
    SYNC_PERIOD: 400   # TODO: a small sync period increases performance in some cases, but it also slows down the data collection process
    RECORD_PERIOD: 100
    N_EVALUATION: 10
    logger: True

    # distributed algo params
    n_learner_cpus: 3
    n_learner_gpus: .3
    n_workers: 5
    n_worker_cpus: 1
    n_worker_gpus: .1
    deterministic_evaluation: False
    run_mode: nsteps

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    target_update_period: 1500

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    q_lr: 2.5e-4
    actor_lr: 2.5e-4
    temp_lr: 2.5e-4
    prior_lr: 1.e-3
    epsilon: 3.125e-4
    
    # arguments for PER
    per_alpha: .6
    per_epsilon: 1e-4
    use_is_ratio: &is False

replay:
    replay_type: *replay
    seqlen: 50
    n_envs: *ne
    # arguments for PER
    beta0: .4
    beta_steps: 2e6
    to_update_top_priority: True
    return_IS_ratio: *is

    # arguments for general replay
    n_steps: *nsteps
    max_steps: 5
    gamma: *gamma
    batch_size: *bs
    min_size: 1600
    capacity: 2.5e5
    has_next_obs: True
