---
env:
    name: procgen_coinrun
    frame_skip: 2
    gray_scale: True
    frame_stack: 4

model:
    cnn: 
        cnn: impala
    actor:
        units_list: [512]
        norm: none
        activation: relu
    q:
        units_list: [512]
        norm: none
        activation: relu
    temperature:
        temp_type: 'variable'
        value: 0
        
agent:
    algorithm: &algo sac4
    replay_type: &replay 'uniform'
    gamma: &gamma .99
    polyak: .995
    act_eps: 0
    # target_entropy: .3
    
    MAX_STEPS: 8e6
    TRAIN_PERIOD: 64
    EVAL_PERIOD: 5e5
    LOG_PERIOD: 5e4
    N_UPDATES: 1

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    RECORD: True

    target_update_period: 2000

    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 3e-4
    temp_lr: 3e-4
    
    # arguments for PER
    per_alpha: .5
    per_epsilon: 1e-4

replay:
    replay_type: *replay
    # arguments for PER
    beta0: .4
    beta_steps: 5e4
    to_update_top_priority: True

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: 64
    min_size: 2e4
    capacity: 1e5
    has_next_obs: False
