---
env:
    name: dmc_walker_walk
    log_episode: True
    n_envs: 1
    frame_skip: 2
    precision: &prec 16
model:
    encoder:
        has_cnn: True
    rssm:
        stoch_size: 30
        deter_size: 200
        hidden_size: 200
        activation: elu
    reward:
        units_list: [400, 400]
        activation: elu
    decoder:
        has_cnn: True
    actor:
        units_list: [400, 400, 400, 400]
        LOG_STD_MIN: -20
        LOG_STD_MAX: 2
        activation: elu
        init_std: 5
        min_std: 1.e-4
        mean_scale: 5
    value:
        units_list: [400, 400, 400]
        activation: elu
    temperature:
        temp_type: constant
        value: .01
    # uncomment the following code for atari games
    # discount:
    #     units_list: [400, 400, 400]
    #     activation: elu
agent:
    algorithm: &algo dreamer2
    polyak: .995
    batch_size: &bs 50

    # These params are not supported here, see seed1
    store_state: True
    burn_in: True
    batch_len: &bl 90
    burn_in_len: 40

    MAX_STEPS: 5.e+6
    LOG_INTERVAL: 1000
    EVAL_INTERVAL: 10000
    TRAIN_INTERVAL: 1000
    N_UPDATES: 100
    log_images: True

    # model
    free_nats: 3.
    kl_scale: 1.
    discount_scale: 10.
    # behavior
    horizon: 15
    gamma: &gamma 0.99
    lambda: .95
    # act_epsilon: .3

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    # arguments for optimizer
    optimizer: adam
    clip_norm: 100.
    weight_decay: 0.
    model_lr: 6.e-4
    actor_lr: 8.e-5
    value_lr: 8.e-5
    temp_lr: 3.e-4

replay:
    type: episodic                      # proportional or uniform

    # arguments for general replay
    batch_size: *bs
    batch_len: *bl
    max_episodes: 800
    min_episodes: 5
    save: True
    