---
env:
    name: procgen_coinrun
    frame_skip: 2
    gray_scale: True
    frame_stack: 4

model:
    encoder:
        cnn_name: mbse
        obs_range: [-1, 1]
        channels: [16, 32, 32, 64]
        expansion_ratio: [4, 4, 4, 4]
        reduction_ratio: 1
        norm: null
        out_size: null
        kernel_initializer: glorot_uniform
        activation: relu
    fpn:
        N: &N 32
        kernel_initializer: glorot_uniform
    iqn:
        kernel_initializer: glorot_uniform
        units_list: [512]
        activation: relu
        layer_type: dense
        duel: False

        tau_embed_size: 64
        phi_activation: relu

agent:
    algorithm: &algo fqf
    replay_type: &replay 'uniform'
    batch_size: &bs 32
    gamma: &gamma 0.99
    n_steps: &nsteps 1      # n-step target
    precision: &prec 32
    schedule_act_eps: True
    act_eps: 0.01
    eval_act_eps: 0

    MAX_STEPS: 8e6      # maximum env frames
    TRAIN_PERIOD: 128    # #frames
    EVAL_PERIOD: 5e5
    LOG_PERIOD: 1e4
    N_UPDATES: 1
    RECORD: True

    normalize_reward: False

    # IQN params
    N: *N               # N in paper, num of quantiles for online quantile network
    KAPPA: 1            # 𝜅 in paper, used as the threshold for the huber loss

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    target_update_period: 2000  # trainning step
    tbo: False                              # transformed Bellman Operator
    
    # arguments for optimizer
    iqn_opt: adam
    schedule_lr: False
    iqn_lr: 5e-5
    fpn_opt: rmsprop
    fpn_lr: 2.5e-9
    ent_coef: .001
    clip_norm: 10
    epsilon: 3.125e-4

    # arguments for PER
    per_alpha: .5
    per_epsilon: 1e-4

replay:
    replay_type: *replay
    precision: 32
    # arguments for PER
    beta0: 0
    to_update_top_priority: True

    # arguments for general replay
    n_steps: *nsteps
    gamma: *gamma
    batch_size: *bs
    min_size: 5e4
    capacity: 1e5
    has_next_obs: False
