---
algorithm: &algo gpo
name: gpo

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
    algorithm: *algo

    MAX_STEPS: 3e6
    n_steps: &nsteps 32
    LOG_PERIOD: 1000
    EVAL_PERIOD: 1000

    RECORD_VIDEO: False
    N_EVAL_EPISODES: 1

    timeout_done: &td False
    update_obs_rms_at_execution: &uorae False

env:
    env_name: &env_name HalfCheetah-v3
    n_runners: &nrunners 4
    n_envs: &nenvs 16
    seed: 0
    reward_min: null
    reward_max: null
    timeout_done: *td
    bound_method: clip
    action_low: null
    action_high: null
    to_rescale: True

agent: {}

strategy:
    train_loop:
        use_dataset: &dataset False
        n_epochs: &nepochs 10
        n_mbs: &nmbs 4
        n_aux_epochs: &naepochs 9
        n_pi: &npi 16
        n_segs: &nsegs 16
        n_aux_mbs_per_seg: &nambs 2
        max_kl: 0            # early stop when max_kl is violated. 0 or null suggests unbound

        # (once reuse null)
        # "once" updates values at the end of each epoch
        # "reuse" updates values using value from train which is staler than once
        # null doesn't update values.
        value_update: null

model:
    rnn_type: &rnn null
    compute_value_at_execution: *td
    sample_size: &ss 16

    encoder: 
        nn_id: null
    rnn:
        nn_id: *rnn
        units: 64
        kernel_initializer: orthogonal
        recurrent_initializer: orthogonal
        use_ln: True
    policy:
        nn_id: policy
        units_list: [64, 64]
        kernel_initializer: orthogonal
        activation: tanh
        norm: null
        eval_act_temp: 1
        out_gain: .01
        init_std: .6065
        out_act: null
    value:
        nn_id: value
        units_list: [64, 64]
        kernel_initializer: orthogonal
        activation: tanh
        norm: null

loss:
    # hyperparams for loss
    ppo_clip_range: .2
    entropy_coef: 0
    aux_l1_coef: 0
    aux_l2_coef: 0
    weighted_l_dist: False
    kl_prior_coef: 0
    new_po_coef: 0
    pg_coef: 1
    js_coef: null
    kl_prior: reverse
    norm_adv: False

    value_loss: mse
    value_clip_range: .2
    value_coef: .5

trainer:
    algorithm: *algo
    sample_size: *ss         # BPTT length
    store_state: True

    optimizer:
        opt_name: adam
        schedule_lr: False
        lr: 3e-4
        clip_norm: .5
        epsilon: 1e-8

actor:
    update_obs_rms_at_execution: *uorae
    update_obs_at_execution: False
    rms:
        obs_names: [obs]
        obs_normalized_axis: [0, 1]
        normalize_obs: True
        obs_clip: 10
        normalize_reward: False
        update_reward_rms_in_time: False
        gamma: &gamma .99

buffer:
    type: ac
    use_dataset: *dataset

    adv_type: gae     # nae or gae
    gamma: *gamma
    lam: .95
    n_runners: *nrunners
    n_envs: *nenvs
    n_steps: *nsteps
    n_epochs: *nepochs
    n_mbs: *nmbs        # number of minibatches
    rnn_type: *rnn
    normalize_value: True
    
    # Trust region arguments
    target_pi:
        target_type: exp
        adv_tau: 1
        alpha: .2
        pr_lower_clip: .2
        pr_upper_clip: .2
        exp_lower_clip: 1
        exp_upper_clip: 1
        adv_lower_clip: 1
        adv_upper_clip: 3
        lin_lower_clip: .5
        lin_upper_clip: 1
        lin_weights: 1
        normalize_adv: False
        zero_center: False
        step_size: .1

    aux_adv_lower_clip: null
    aux_adv_upper_clip: null

    sample_keys: 
        - obs
        - action
        - reward
        - value
        - traj_ret
        - advantage
        - target_prob
        - tr_prob
        - target_prob_prime
        - tr_prob_prime
        - logprob
        - pi_mean
        - pi_std
        - reset
        - discount
        - mask
        - h
        - c
