---
algorithm: &algo zero
name: zero

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
    algorithm: *algo

    MAX_STEPS: 1e7
    n_steps: &nsteps 16
    LOG_PERIOD: 2e3
    EVAL_PERIOD: null

    RECORD_VIDEO: True
    N_EVAL_EPISODES: 1
    size: [256, 256]

env:
    env_name: &env_name sagw-tc
    n_runners: &nrunners 1
    n_envs: &nenvs 1
    step_penalty: -.04
    max_episode_steps: 1e5
    flip_steps: 1e5
    max_stay_still: null

    to_multi_agent: True
    timeout_done: &td True
    life_long: True
    reward_done: False
    use_action_mask: False

agent: {}

strategy:
    algorithm: *algo
    train_loop: {}

model:
    aid: 0
    meta_type: &meta bmg
    rnn_type: &rnn null
    gamma: &gamma .99
    eval_act_temp: 1
    K: &K 0
    L: &L 0

    encoder: 
        nn_id: null
    rnn:
        nn_id: *rnn
    policy:
        nn_id: policy
        units_list: [256, 256]
        w_init: orthogonal
        activation: relu
        norm: null
        out_scale: .01
    value:
        nn_id: value
        units_list: [256, 256]
        w_init: orthogonal
        activation: relu
        norm: null
    meta_params:
        nn_id: meta
        pg_coef:
            outer: 1
            default: 1
            init: null
            act: sigmoid
        entropy_coef:
            outer: 1e-1
            default: 1e-1
            scale: .5
            bias: .1
            init: .5
            act: sigmoid
            net:
                nn_id: mlp
                units_list: [32]
                w_init: orthogonal
                out_scale: .01
                out_b_init: const_0
                activation: relu
        value_coef:
            outer: 1
            default: 1
            scale: 1
            bias: 0
            init: null
            act: sigmoid
        gamma: 
            outer: *gamma
            default: *gamma
            scale: 1
            bias: 0
            init: null
            act: sigmoid
        lam:
            outer: &lam 1
            default: *lam
            scale: 1
            bias: 0
            init: null
            act: sigmoid

loss:
    # hyperparams for value target and advantage
    target_type: vtrace
    c_clip: 1
    rho_clip: 1
    adv_type: vtrace

    # hyperparams for policy optimization
    pg_type: pg
    ppo_clip_range: .2
    use_dice: False
    dice_axis: null
    dice_lam: 1
    kl: forward
    kl_coef: 1
    policy_life_mask: True
    adv_clip: null

    # hyperparams for value learning
    value_loss: mse
    huber_threshold: 1
    value_clip_range: .2
    value_life_mask: False
    stop_target_grads: False

    # hyperparams for meta-learning
    meta_type: *meta

trainer:
    algorithm: *algo
    aid: 0
    n_runners: *nrunners
    n_envs: *nenvs
    n_epochs: &nepochs 1
    n_mbs: &nmbs 1
    n_meta_epochs: 1
    n_steps: *nsteps         # BPTT length
    timeout_done: *td
    meta_type: *meta
    K: *K
    L: *L
    store_state: True

    debug: False

    theta_opt:
        opt_name: sgd
        lr: .1
        clip_norm: 10
    meta_params_opt:
        opt_name: adam
        lr: 1e-3
        eps: 1e-4
        clip_norm: 10

actor:
    update_obs_rms_at_execution: False
    update_obs_at_execution: False
    rms:
        obs_names: [obs, global_state]
        obs_normalized_axis: [0, 1, 2]
        reward_normalized_axis: [0, 1, 2]
        normalize_obs: False
        obs_clip: 10
        normalize_reward: False
        update_reward_rms_in_time: False
        gamma: *gamma

buffer:
    type: ac

    n_runners: *nrunners
    n_envs: *nenvs
    n_steps: *nsteps
    queue_size: 2
    meta_type: *meta
    K: *K
    L: *L
    timeout_done: *td
    rnn_type: *rnn

    sample_keys: 
        - obs
        - action
        - value
        - reward
        - discount
        - reset
        - mu_logprob
        - mu_logits
        - mask
        - h
        - c
