---
env:
    name: LunarLander-v2
    video_path: video
    seed: 0
model:
    q:
        cnn: none #impala
        v_units: [128]
        a_units: [128]
        activation: relu
agent:
    algorithm: &algo d3qn
    gamma: &gamma 0.99
    precision: &prec 32
    # act_eps: .3

    MAX_STEPS: 1.e+7          # maximum training steps
    TRAIN_INTERVAL: 4
    EVAL_INTERVAL: 25000
    LOG_INTERVAL: 10000

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: huber   # huber or mse
    target_update_freq: 1000               # frames
    tbo: False                              # transformed Bellman Operator
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 3.e-3
    clip_norm: 10
    epsilon: 1.5e-4

    # arguments for PER
    per_alpha: 0.5
    per_epsilon: 1.e-4

replay:
    type: uniform      # uniform, proportional
    precision: *prec
    # arguments for PER
    beta0: 0.4
    beta_steps: 1.e+6
    to_update_top_priority: True

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: 512
    min_size: 1.e+4
    capacity: 1.e+6
    has_next_obs: False
