---
env:
    name: LunarLander-v2 #atari_Pong
    video_path: video
    log_video: False
    efficient_envvec: True
    max_episode_steps: 108000
    seed: 0
model:
    q:
        cnn: None #impala
        v_units: [64, 64] #[256]
        a_units: [64, 64] #[256]
        activation: relu
agent:
    algorithm: &algo d3qn
    gamma: &gamma 0.99

    MAX_STEPS: 1.e+7          # maximum training steps
    TRAIN_INTERVAL: 4
    EVAL_INTERVAL: 10000 # 250000
    LOG_INTERVAL: 1000

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: huber   # huber or mse
    target_update_freq: 3000 # 32000    # frames
    tbo: False                               # transformed Bellman Operator
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 1.e-3   #6.25e-5
    clip_norm: 10
    epsilon: 0.0003125

    # arguments for PER
    per_alpha: 0.5
    per_epsilon: 1.e-4

replay:
    type: proportional      # uniform, proportional
    # arguments for PER
    beta0: 0.4
    beta_steps: 1.e+6
    to_update_top_priority: True

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: 256 # 32
    min_size: 1.e+4 # 8e4
    capacity: 1.e+6
    has_next_obs: False
