---
env:
    name: LunarLander-v2
    precision: &prec 32
    seed: 0
model:
    q:
        cnn: none
        v_units: [128, 64]
        a_units: [128, 64]
        activation: relu
        layer_type: dense
        duel: True
agent:
    algorithm: &algo d3qn
    gamma: &gamma 0.99
    precision: *prec
    schedule_eps: False
    act_eps: 0.3

    MAX_STEPS: 1.e+8          # maximum training steps
    TRAIN_INTERVAL: 1          # #frames = 4 agent step when frame skip = 4
    EVAL_INTERVAL: 10000
    LOG_INTERVAL: 1000

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo

    loss_type: huber   # huber or mse
    target_update_freq: 1000               # #frames = 8000 agent step when frame skip = 4
    tbo: False                              # transformed Bellman Operator
    
    # arguments for optimizer
    optimizer: adam
    schedule_lr: False
    lr: 3.e-4
    clip_norm: 10
    epsilon: 1.5e-4

    # arguments for PER
    per_alpha: 0.5
    per_epsilon: 1.e-4

replay:
    type: proportional      # uniform, proportional
    precision: *prec
    # arguments for PER
    beta0: 0.4
    to_update_top_priority: True

    # arguments for general replay
    n_steps: 3
    gamma: *gamma
    batch_size: 256
    min_size: 1.e+4
    capacity: 1.e+5
    has_next_obs: False
