---
algorithm: &algo lka_kl
name: lka_kl
info: ppo

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
    algorithm: *algo

    MAX_STEPS: 1e7
    n_steps: &nsteps 100
    LOG_PERIOD: 2e5
    EVAL_PERIOD: 2e5

    RECORD_VIDEO: False
    N_EVAL_EPISODES: 5
    size: [256, 256]

    n_imaginary_runs: 1
    imaginary_rollout: sim

env:
    env_name: &env_name ma_mujoco-HalfCheetah_2x3
    n_runners: &nrunners 1
    n_envs: &nenvs 40
    max_episode_steps: 1000
    timeout_done: &td False
    env_args:
        agent_conf: 2x3
        agent_obsk: 0

agent: {}

monitor:
    use_tensorboard: True

strategy:
    algorithm: *algo
    train_loop: {}

model:
    aid: 0
    gamma: &gamma .99

    policy:
        nn_id: policy
        units_list: [64, 64]
        w_init: orthogonal
        activation: relu
        norm: null
        out_scale: .01
        rnn_type: &prnn null
        rnn_units: 64
        init_std: .2
        sigmoid_scale: False
        std_x_coef: 1.
        std_y_coef: .5
        use_feature_norm: True
    value:
        nn_id: value
        units_list: [64, 64]
        w_init: orthogonal
        activation: relu
        norm: null
        rnn_type: &vrnn null
        rnn_units: 64
        use_feature_norm: True

loss:
    # hyperparams for value target and advantage
    target_type: gae
    c_clip: 1
    rho_clip: 1
    adv_type: gae
    norm_adv: True
    popart: &popart True

    prnn_bptt: 10
    vrnn_bptt: 10

    # hyperparams for policy optimization
    pg_type: ppo
    ppo_clip_range: .2
    kl_type: reverse
    kl_coef: 0
    policy_sample_mask: True

    # hyperparams for value learning
    value_loss: clip_huber
    huber_threshold: 10
    value_clip_range: .2
    value_sample_mask: False

    stats:
        gamma: *gamma
        lam: &lam .95
        pg_coef: 1
        entropy_coef: .001
        value_coef: 1

trainer:
    algorithm: *algo
    aid: 0
    n_runners: *nrunners
    n_envs: *nenvs
    n_epochs: &nepochs 5
    n_imaginary_epochs: 5
    n_mbs: &nmbs 40
    n_steps: *nsteps         # BPTT length

    popart: *popart

    # policy_opt:
    #     opt_name: adam
    #     lr: 5e-6
    #     clip_norm: 10
    #     eps: 1e-5
    # value_opt:
    #     opt_name: adam
    #     lr: 5e-3
    #     clip_norm: 10
    #     eps: 1e-5
    theta_opt:
        opt_name: adam
        lr: 1e-3
        clip_norm: 10
        eps: 1e-5

actor:
    update_obs_rms_at_execution: False
    update_obs_at_execution: False
    rms:
        obs_names: [obs, global_state]
        obs_normalized_axis: [0, 1, 2]
        reward_normalized_axis: [0, 1, 2]
        normalize_obs: False
        obs_clip: 10
        normalize_reward: False
        update_reward_rms_in_time: False
        gamma: *gamma

buffer:
    type: ac

    n_runners: *nrunners
    n_envs: *nenvs
    n_steps: *nsteps
    queue_size: 2
    timeout_done: *td

    gamma: *gamma
    lam: *lam

    sample_keys: 
        - obs
        - action
        - value
        - reward
        - discount
        - reset
        - mu_logprob
        - mu_loc
        - mu_scale
        - state_reset
        - state
